# 1. 멜론 차트 Top100 노래제목과 가수명을 크롤링해보자~!

In [2]:
import requests
from bs4 import BeautifulSoup as bs
import pandas as pd

In [3]:
U_A = {"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36"}

In [411]:
# 통신 연결
res = requests.get("https://www.melon.com/chart/index.htm", headers=U_A)
res

In [412]:
# 파싱
soup = bs(res.text, "lxml")

### 1. 가수명

In [413]:
name = soup.select("div.ellipsis.rank02 > span") # 헐.... 안쪽에 구조 더 있었음....
print(name[0])

print(len(name))

for i in name:
    print(i.text)

<span class="checkEllipsis" style="display:none"><a href="javascript:melon.link.goArtistDetail('756531');" title="화사 (HWASA) - 페이지 이동">화사 (HWASA)</a></span>
100
화사 (HWASA)
한로로
WOODZ
다비치
카더가든
NMIXX
HUNTR/X, EJAE, AUDREY NUNA, REI AMI, KPop Demon Hunters Cast
LE SSERAFIM (르세라핌), j-hope
한로로
ALLDAY PROJECT
이찬혁
우디 (Woody)
BLACKPINK
로이킴
아일릿(ILLIT)
조째즈
노아주다 (noahjooda)
프로미스나인
ALLDAY PROJECT
성시경
제니 (JENNIE)
AKMU (악뮤)
G-DRAGON
로제 (ROSÉ)
이창섭
TWS (투어스)
로이킴
10CM
KPop Demon Hunters Cast, Danny Chung, Saja Boys, Andrew Choi, Neckwav, Kevin Woo, samUIL Lee
Disney, Shakira
박다혜, 마크툽 (MAKTUB)
aespa
황가람
이무진
BOYNEXTDOOR
폴킴
DAY6 (데이식스)
너드커넥션 (Nerd Connection)
EXO
IVE (아이브)
임영웅
이클립스 (ECLIPSE)
DAY6 (데이식스)
DAY6 (데이식스)
IVE (아이브)
정승환
BOYNEXTDOOR
이창섭
로제 (ROSÉ), Bruno Mars
Hearts2Hearts (하츠투하츠)
에픽하이 (EPIK HIGH)
오반(OVAN)
마크툽 (MAKTUB)
Kenshi Yonezu
아이유
DAY6 (데이식스)
먼데이 키즈, 이이경
아이유
아샤트리, 이예은, 전건호
Lady Gaga, Bruno Mars
TWS (투어스)
aespa
멜로망스
잔나비
이무진
G-DRAGON
이무진
경서예지, 전건호
Hearts2Hearts (하츠투하츠)
이창섭
범진
IVE (아이브)
아일릿(ILLIT)
박재정
아일릿(ILLIT)
이예은, 아샤트리, 전건호
aespa
aespa
나윤권, 도경수(D.O.)
이무진
임재현
임영웅
정국
임영웅
DK(디셈버)
NewJeans
순순희(지환)
다영 (DAYOUNG)
지코 (ZICO), Lilas
PLAVE
QWER
ALLDAY PROJECT
임영웅
EXO
ALLDAY PROJECT
임현정
임영웅
임영웅
BABYMONSTER
PLAVE

### 2. 노래 제목

In [414]:
mel = soup.select("span>a")
print(mel[0])
print(mel[1])

<a href="javascript:melon.play.playSong('1000002721',600287375);" title="Good Goodbye 재생">Good Goodbye</a>
<a href="javascript:melon.link.goArtistDetail('756531');" title="화사 (HWASA) - 페이지 이동">화사 (HWASA)</a>

In [415]:
titles = soup.select("div.ellipsis.rank01")

print(len(titles))

for i in titles:
    print(i.text.strip())

100
Good Goodbye
사랑하게 될 거야
Drowning
타임캡슐
그대 작은 나의 세상이 되어
Blue Valentine
Golden
SPAGHETTI (feat. j-hope of BTS)
0+0
ONE MORE TIME
멸종위기사랑
어제보다 슬픈 오늘
뛰어(JUMP)
달리 표현할 수 없어요
NOT CUTE ANYMORE
모르시나요(PROD.로코베리)
힙합보단 사랑, 사랑보단 돈 (Feat. 베이식)
하얀 그리움
FAMOUS
너의 모든 순간
like JENNIE
어떻게 이별까지 사랑하겠어, 널 사랑하는 거지
HOME SWEET HOME (feat. 태양, 대성)
toxic till the end
천상연
OVERDRIVE
내게 사랑이 뭐냐고 물어본다면
너에게 닿기를
Soda Pop
Zoo (From "Zootopia 2"/Soundtrack Version)
시작의 아이 ❍
Whiplash
나는 반딧불
청춘만화
오늘만 I LOVE YOU
모든 날, 모든 순간 (Every day, Every Moment)
HAPPY
그대만 있다면 (여름날 우리 X 너드커넥션 (Nerd Connection))
첫 눈
REBEL HEART
사랑은 늘 도망가
소나기
예뻤어
한 페이지가 될 수 있게
XOXZ
눈사람
Hollywood Action
한번 더 이별
APT.
FOCUS
Love Love Love (Feat. Yoong Jin Of Casker)
Flower
시작의 아이
IRIS OUT
Love wins all
Welcome to the Show
운명 (2025)
Never Ending Story
그래 늦지 않았어 (2025)
Die With A Smile
첫 만남은 계획대로 되지 않아
Rich Man
사랑인가 봐
주저하는 연인들을 위해
눈이 오잖아(Feat.헤이즈)
TOO BAD (feat. Anderson .Paak)
청혼하지 않을 이유를 못 찾았어
다정히 내 이름을 부르면
STYLE
365일
인사
I AM
Magnetic
헤어지자 말해요
빌려온 고양이 (Do the Dance)
MY LOVE(2025)
Supernova
Dirty Work
나였으면
에피소드
비의 랩소디
순간을 영원처럼
Seven (feat. Latto) - Clean Ver.
우리들의 블루스
가만히 눈을 감고
Hype Boy
슬픈 초대장
body
DUET
이 밤을 빌려 말해요
고민중독
LOOK AT ME
다시 만날 수 있을까
Crown
WICKED
사랑은 봄비처럼...이별은 겨울비처럼...
들꽃이 될게요
그댈 위한 멜로디
DRIP
BBUU!

## 정리
- 내가 수집하고자 하는 데이터의 태그명이나 구분자(id, class)를 통해서 접근하고, 범위가 더 넓다면 한 계층씩 올라가면서 범위를 좁혀주는 작업을 진행해야 함
- class명 중간에 공백이 있다면 다중 클래스이므로 클래스 각각에 대해 .을 붙여서 명시해줘야 함
- 가수명의 경우 듀엣곡은 2명 이상의 가수가 각각 선택되므로, 하나로 선택될 수 있게 윗 계층의 태그와 선택자만으로 select 해주는 것도 방법
- 즉, 크롤링을 잘하기 위해서는 수집하려는 웹 페이지의 HTML 코드 계층을 잘 분석하고 접근해야 함!

## 수집한 데이터 정제

In [88]:
print(type(titles))
print(type(name))

# 겉으로 보기에는 자료형이 리스트로 보였지만 실제로는 BS내부에서 사용하는 ResultSet 이라는 객체임
# BS내부에서 사용하는 특수한 리스트로 pandas나 matplotlib에 바로 사용할 수 없어서 리스트로 변형해야 함~!

<class 'bs4.element.ResultSet'>
<class 'bs4.element.ResultSet'>

In [418]:
titles_list, artist_list =[], [] # 빈 리스트 생성

# 반복문으로 컨텐츠(텍스트)만 추출하여 빈 리스트에 담기
for i in range(len(titles)): # titles나 name 모두 100개로 동일해서 뭘 사용해도 상관없음
    titles_list.append(titles[i].text.strip())
    artist_list.append(name[i].text.strip())

    # 보기 좋게 출력
    print(titles[i].text+ '-' +name[i].text)

Good Goodbye
-화사 (HWASA)

사랑하게 될 거야
-한로로

Drowning
-WOODZ

타임캡슐
-다비치

그대 작은 나의 세상이 되어
-카더가든

Blue Valentine
-NMIXX

Golden
-HUNTR/X, EJAE, AUDREY NUNA, REI AMI, KPop Demon Hunters Cast

SPAGHETTI (feat. j-hope of BTS)
-LE SSERAFIM (르세라핌), j-hope

0+0
-한로로

ONE MORE TIME
-ALLDAY PROJECT

멸종위기사랑
-이찬혁

어제보다 슬픈 오늘
-우디 (Woody)

뛰어(JUMP)
-BLACKPINK

달리 표현할 수 없어요
-로이킴

NOT CUTE ANYMORE
-아일릿(ILLIT)

모르시나요(PROD.로코베리)
-조째즈

힙합보단 사랑, 사랑보단 돈 (Feat. 베이식)
-노아주다 (noahjooda)

하얀 그리움
-프로미스나인

FAMOUS
-ALLDAY PROJECT

너의 모든 순간
-성시경

like JENNIE
-제니 (JENNIE)

어떻게 이별까지 사랑하겠어, 널 사랑하는 거지
-AKMU (악뮤)

HOME SWEET HOME (feat. 태양, 대성)
-G-DRAGON

toxic till the end
-로제 (ROSÉ)

천상연
-이창섭

OVERDRIVE
-TWS (투어스)

내게 사랑이 뭐냐고 물어본다면
-로이킴

너에게 닿기를
-10CM

Soda Pop
-KPop Demon Hunters Cast, Danny Chung, Saja Boys, Andrew Choi, Neckwav, Kevin Woo, samUIL Lee

Zoo (From "Zootopia 2"/Soundtrack Version)
-Disney, Shakira

시작의 아이 ❍
-박다혜, 마크툽 (MAKTUB)

Whiplash
-aespa

나는 반딧불
-황가람

청춘만화
-이무진

오늘만 I LOVE YOU
-BOYNEXTDOOR

모든 날, 모든 순간 (Every day, Every Moment)
-폴킴

HAPPY
-DAY6 (데이식스)

그대만 있다면 (여름날 우리 X 너드커넥션 (Nerd Connection))
-너드커넥션 (Nerd Connection)

첫 눈
-EXO

REBEL HEART
-IVE (아이브)

사랑은 늘 도망가
-임영웅

소나기
-이클립스 (ECLIPSE)

예뻤어
-DAY6 (데이식스)

한 페이지가 될 수 있게
-DAY6 (데이식스)

XOXZ
-IVE (아이브)

눈사람
-정승환

Hollywood Action
-BOYNEXTDOOR

한번 더 이별
-이창섭

APT.
-로제 (ROSÉ), Bruno Mars

FOCUS
-Hearts2Hearts (하츠투하츠)

Love Love Love (Feat. Yoong Jin Of Casker)
-에픽하이 (EPIK HIGH)

Flower
-오반(OVAN)

시작의 아이
-마크툽 (MAKTUB)

IRIS OUT
-Kenshi Yonezu

Love wins all
-아이유

Welcome to the Show
-DAY6 (데이식스)

운명 (2025)
-먼데이 키즈, 이이경

Never Ending Story
-아이유

그래 늦지 않았어 (2025)
-아샤트리, 이예은, 전건호

Die With A Smile
-Lady Gaga, Bruno Mars

첫 만남은 계획대로 되지 않아
-TWS (투어스)

Rich Man
-aespa

사랑인가 봐
-멜로망스

주저하는 연인들을 위해
-잔나비

눈이 오잖아(Feat.헤이즈)
-이무진

TOO BAD (feat. Anderson .Paak)
-G-DRAGON

청혼하지 않을 이유를 못 찾았어
-이무진

다정히 내 이름을 부르면
-경서예지, 전건호

STYLE
-Hearts2Hearts (하츠투하츠)

365일
-이창섭

인사
-범진

I AM
-IVE (아이브)

Magnetic
-아일릿(ILLIT)

헤어지자 말해요
-박재정

빌려온 고양이 (Do the Dance)
-아일릿(ILLIT)

MY LOVE(2025)
-이예은, 아샤트리, 전건호

Supernova
-aespa

Dirty Work
-aespa

나였으면
-나윤권, 도경수(D.O.)

에피소드
-이무진

비의 랩소디
-임재현

순간을 영원처럼
-임영웅

Seven (feat. Latto) - Clean Ver.
-정국

우리들의 블루스
-임영웅

가만히 눈을 감고
-DK(디셈버)

Hype Boy
-NewJeans

슬픈 초대장
-순순희(지환)

body
-다영 (DAYOUNG)

DUET
-지코 (ZICO), Lilas

이 밤을 빌려 말해요
-PLAVE

고민중독
-QWER

LOOK AT ME
-ALLDAY PROJECT

다시 만날 수 있을까
-임영웅

Crown
-EXO

WICKED
-ALLDAY PROJECT

사랑은 봄비처럼...이별은 겨울비처럼...
-임현정

들꽃이 될게요
-임영웅

그댈 위한 멜로디
-임영웅

DRIP
-BABYMONSTER

BBUU!
-PLAVE

In [95]:
len(titles_list), len(artist_list)

(100, 100)

## DataFrame화 시키기

In [110]:
# 데이터프레임을 만들 딕셔너리 선언
melon_dic = {'노래제목':titles_list, '가수명':artist_list}
melon_dic

{'노래제목': ['Good Goodbye',
  '사랑하게 될 거야',
  'Drowning',
  '그대 작은 나의 세상이 되어',
  '타임캡슐',
  'Blue Valentine',
  'Golden',
  'SPAGHETTI (feat. j-hope of BTS)',
  'ONE MORE TIME',
  '0+0',
  '멸종위기사랑',
  '어제보다 슬픈 오늘',
  '달리 표현할 수 없어요',
  '뛰어(JUMP)',
  'NOT CUTE ANYMORE',
  '하얀 그리움',
  '힙합보단 사랑, 사랑보단 돈 (Feat. 베이식)',
  '모르시나요(PROD.로코베리)',
  'FAMOUS',
  '너의 모든 순간',
  'like JENNIE',
  '어떻게 이별까지 사랑하겠어, 널 사랑하는 거지',
  'HOME SWEET HOME (feat. 태양, 대성)',
  'Zoo (From "Zootopia 2"/Soundtrack Version)',
  'OVERDRIVE',
  '천상연',
  'toxic till the end',
  '내게 사랑이 뭐냐고 물어본다면',
  'Soda Pop',
  '너에게 닿기를',
  '시작의 아이 ❍',
  '사랑은 늘 도망가',
  '나는 반딧불',
  '청춘만화',
  'Whiplash',
  '첫 눈',
  'HAPPY',
  '모든 날, 모든 순간 (Every day, Every Moment)',
  '오늘만 I LOVE YOU',
  'REBEL HEART',
  '그대만 있다면 (여름날 우리 X 너드커넥션 (Nerd Connection))',
  '한 페이지가 될 수 있게',
  '소나기',
  '예뻤어',
  '한번 더 이별',
  '눈사람',
  'XOXZ',
  '그래 늦지 않았어 (2025)',
  '시작의 아이',
  '순간을 영원처럼',
  'APT.',
  '365일',
  'IRIS OUT',
  'Hollywood Action',
  'Love Love Love (Feat. Yoong Jin Of Casker)',
  'Flower',
  '운명 (2025)',
  'Love wins all',
  'Welcome to the Show',
  '우리들의 블루스',
  'FOCUS',
  'Crown',
  'Die With A Smile',
  '주저하는 연인들을 위해',
  'Never Ending Story',
  '눈이 오잖아(Feat.헤이즈)',
  '청혼하지 않을 이유를 못 찾았어',
  '첫 만남은 계획대로 되지 않아',
  'TOO BAD (feat. Anderson .Paak)',
  '다시 만날 수 있을까',
  '사랑인가 봐',
  'Rich Man',
  '다정히 내 이름을 부르면',
  '나였으면',
  '인사',
  '이 밤을 빌려 말해요',
  '들꽃이 될게요',
  'STYLE',
  '헤어지자 말해요',
  'I AM',
  '그댈 위한 멜로디',
  'MY LOVE(2025)',
  '에피소드',
  'Seven (feat. Latto) - Clean Ver.',
  'Dirty Work',
  'Magnetic',
  'DUET',
  '빌려온 고양이 (Do the Dance)',
  '가만히 눈을 감고',
  'Supernova',
  '비의 랩소디',
  '슬픈 초대장',
  '사랑은 봄비처럼...이별은 겨울비처럼...',
  '고민중독',
  'LOOK AT ME',
  'body',
  'Hype Boy',
  '비가 와서',
  'WICKED',
  'BBUU!'],
 '가수명': ['화사 (HWASA)',
  '한로로',
  'WOODZ',
  '카더가든',
  '다비치',
  'NMIXX',
  'HUNTR/X, EJAE, AUDREY NUNA, REI AMI, KPop Demon Hunters Cast',
  'LE SSERAFIM (르세라핌), j-hope',
  'ALLDAY PROJECT',
  '한로로',
  '이찬혁',
  '우디 (Woody)',
  '로이킴',
  'BLACKPINK',
  '아일릿(ILLIT)',
  '프로미스나인',
  '노아주다 (noahjooda)',
  '조째즈',
  'ALLDAY PROJECT',
  '성시경',
  '제니 (JENNIE)',
  'AKMU (악뮤)',
  'G-DRAGON',
  'Disney, Shakira',
  'TWS (투어스)',
  '이창섭',
  '로제 (ROSÉ)',
  '로이킴',
  'KPop Demon Hunters Cast, Danny Chung, Saja Boys, Andrew Choi, Neckwav, Kevin Woo, samUIL Lee',
  '10CM',
  '박다혜, 마크툽 (MAKTUB)',
  '임영웅',
  '황가람',
  '이무진',
  'aespa',
  'EXO',
  'DAY6 (데이식스)',
  '폴킴',
  'BOYNEXTDOOR',
  'IVE (아이브)',
  '너드커넥션 (Nerd Connection)',
  'DAY6 (데이식스)',
  '이클립스 (ECLIPSE)',
  'DAY6 (데이식스)',
  '이창섭',
  '정승환',
  'IVE (아이브)',
  '아샤트리, 이예은, 전건호',
  '마크툽 (MAKTUB)',
  '임영웅',
  '로제 (ROSÉ), Bruno Mars',
  '이창섭',
  'Kenshi Yonezu',
  'BOYNEXTDOOR',
  '에픽하이 (EPIK HIGH)',
  '오반(OVAN)',
  '먼데이 키즈, 이이경',
  '아이유',
  'DAY6 (데이식스)',
  '임영웅',
  'Hearts2Hearts (하츠투하츠)',
  'EXO',
  'Lady Gaga, Bruno Mars',
  '잔나비',
  '아이유',
  '이무진',
  '이무진',
  'TWS (투어스)',
  'G-DRAGON',
  '임영웅',
  '멜로망스',
  'aespa',
  '경서예지, 전건호',
  '나윤권, 도경수(D.O.)',
  '범진',
  'PLAVE',
  '임영웅',
  'Hearts2Hearts (하츠투하츠)',
  '박재정',
  'IVE (아이브)',
  '임영웅',
  '이예은, 아샤트리, 전건호',
  '이무진',
  '정국',
  'aespa',
  '아일릿(ILLIT)',
  '지코 (ZICO), Lilas',
  '아일릿(ILLIT)',
  'DK(디셈버)',
  'aespa',
  '임재현',
  '순순희(지환)',
  '임현정',
  'QWER',
  'ALLDAY PROJECT',
  '다영 (DAYOUNG)',
  'NewJeans',
  '임영웅',
  'ALLDAY PROJECT',
  'PLAVE']}

In [111]:
# 딕셔너리로 DF 생성
melon_df = pd.DataFrame(melon_dic, index=range(1, 101))
melon_df.index.name ='순위' # 인덱스 명칭 지정
melon_df

                노래제목             가수명
순위
1       Good Goodbye      화사 (HWASA)
2          사랑하게 될 거야             한로로
3           Drowning           WOODZ
4    그대 작은 나의 세상이 되어            카더가든
5               타임캡슐             다비치
..               ...             ...
96              body    다영 (DAYOUNG)
97          Hype Boy        NewJeans
98             비가 와서             임영웅
99            WICKED  ALLDAY PROJECT
100            BBUU!           PLAVE

[100 rows x 2 columns]

## 만든 DF를 csv 파일로 내보내기

In [112]:
# to_csv: DF를 csv 파일로 내보내는 함수 (다른 확장자명으로도 저장 가능)
# encoding='utf-8' 한글 전용 인코딩 방식
melon_df.to_csv('멜론차트TOP100.csv', encoding='utf-8')

# 2. 사람인 신입 구인광고 데이터 수집하기
- HOT100 중에서 신입을 채용하는 TOP10 기업의 데이터를 수집해보자~!

In [183]:
res = requests.get("https://www.saramin.co.kr/zf_user/jobs/hot100", headers=U_A)
res

In [184]:
soup = bs(res.text, 'lxml')
soup

<!DOCTYPE html>
<html lang="ko">
<head>
<title>전체 신입 채용정보 | 인기공고 HOT100 - 사람인</title> <meta content="IE=Edge" http-equiv="X-UA-Compatible"/>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<meta content="ko-KR" http-equiv="Content-Language"/>
<meta content="86455485e27cab6986d130e4c3b90c5b516820d1" name="naver-site-verification"/>
<meta content="가장 인기있는 전체 신입 채용공고 확인하고 취업하세요! - 인기공고 HOT 100 사람인" name="Description"/>
<meta content="사람인" name="writer"/>
<meta content="전체 신입 인기공고 HOT100, 직업, 직무, 경영, 사무, 영업, IT, 디자인, 서비스, 생산, 제조, 건설, 유통, 미디어, 교육, 전문직, 근무지역, 서울, 경기, 인천, 부산, 학력, 고졸, 초대졸, 대졸, 기업유형, 대기업, 공사·공기업, 외국계기업, 스타트업, 중견기업, 중소기업, 이직, 신입, 경력, 공채, 사람인, 취업, 채용, 공채" name="keywords"/>
<meta content="nosublinks" name="naver"/> <meta content="전체 신입 채용정보 | 인기공고 HOT100 - 사람인" property="og:title"/>
<meta content="사람인" property="og:site_name"/>
<meta content="website" property="og:type"/>
<meta content="http://www.saraminimage.co.kr/logo/saraminsnslogo.png" property="og:image"/>
<meta content="200" property="og:image:width"/>
<meta content="200" property="og:image:height"/>
<meta content="가장 인기있는 전체 신입 채용공고 확인하고 취업하세요! - 인기공고 HOT 100 사람인" property="og:description"/>
<meta content="https://www.saramin.co.kr/zf_user/jobs/hot100" property="og:url"/>
<meta content="ko_KR" property="og:locale"/>
<meta content="1593727887570039" property="fb:app_id"/> <link href="android-app://kr.co.saramin.brandapp/https/m.saramin.co.kr/jobs/hot100" rel="alternate"/>
<link href="/sri_css/layout.css?v=20260115103211" media="all" rel="stylesheet" type="text/css"/>
<link href="https://www.saramin.co.kr/zf_user/jobs/hot100" rel="canonical"/>
<link href="ios-app://739013038/https/m.saramin.co.kr/jobs/hot100" rel="alternate"/>
<link href="https://m.saramin.co.kr/jobs/hot100" media="only screen and (max-width: 640px)" rel="alternate" title="mobile optimized version" type="text/html"/>
<link href="/sri_css/pattern.css?v=20260115103211" media="all" rel="stylesheet" type="text/css"/>
<link href="/sri_css/header_default.css?v=20260115103211" media="all" rel="stylesheet" type="text/css"/>
<link href="/sri_css/gnb_default_override.css?v=20260115103211" media="all" rel="stylesheet" type="text/css"/>
<link href="/sri_css/common_ui_keeping.css?v=20260115103211" media="all" rel="stylesheet" type="text/css"/>
<link href="/sri_css/components.css?v=20260115103211" media="all" rel="stylesheet" type="text/css"/>
<link href="/sri_css/jobs-hot100.css?v=20260115103211" media="all" rel="stylesheet" type="text/css"/>
<link href="/sri_css/jobs-recruit.css?v=20260115103211" media="screen, print" rel="stylesheet" type="text/css"/>
<link href="/sri_css/powerlink.css?v=20260115103211" media="all" rel="stylesheet" type="text/css"/>
<link href="/favicon.ico?ver=3" rel="favicon"/>
<link href="/favicon.ico?ver=3" rel="icon" type="image/x-icon"/>
<link href="/favicon.ico?ver=3" rel="shortcut icon" type="image/x-icon"/> <script src="//www.saraminimage.co.kr/js/libs/jquery-1.11.1.min.js" type="text/javascript"></script>
<script type="text/javascript">var $j = jQuery.noConflict();</script>
<script src="/js/libs/saramin/common.js?v=20260115103211" type="text/javascript"></script>
<!--[if lt IE 9]> <script type="text/javascript" src="//www.saramin.co.kr/js/html5shiv.min.js"></script><![endif]-->
<script src="//www.saraminimage.co.kr/js/libs/jquery.tinyscrollbar.min.js" type="text/javascript"></script>
<script src="/js/ui-component.js?v=20260115103211" type="text/javascript"></script>
<script src="/js/layout/default-layout.js?v=20260115103211" type="text/javascript"></script>
<script src="/js/company-info/sri-certification/lib/polyfill.js?v=20260115103211" type="text/javascript"></script>
<script src="https://ssl.pstatic.net/adimg3.search/adpost/js/adpost_show_ads_v2.min.js" type="text/javascript"></script>
<script src="/js/powerlink_ui.js?v=20260115103211" type="text/javascript"></script> <script type="text/javascript">
    var nestads = window.nestads || { cmd: [] };

    document.addEventListener('DOMContentLoaded', function () {
        var useSSL = 'https:' === document.location.protocol;
        var $script = document.createElement('script');
        $script.src = (useSSL ? 'https:' : 'http:') + '//static.nestads.com/sdk/js/v2.2.6/nestads-sdk.js';
        document.body.appendChild($script);
    });
</script>
<script type="text/javascript">
    (function() {
        nestads.cmd.push(() => {
            const scriptList = ([{"inventory_code":"recruit-view_728x90","location_id":"9af1ea08-8d9f-44bd-a927-429801a8eab3","width":"728","height":"90"},{"inventory_code":"area-list_728x90","location_id":"9579c10f-0444-4828-a538-23af02ff5716","width":"728","height":"90"},{"inventory_code":"etc_728x90","location_id":"9579c10f-0444-4828-a538-23af02ff5716","width":"728","height":"90"},{"inventory_code":"CS_728x90","location_id":"9579c10f-0444-4828-a538-23af02ff5716","width":"728","height":"90"},{"inventory_code":"profession-list_728x90","location_id":"9579c10f-0444-4828-a538-23af02ff5716","width":"728","height":"90"},{"inventory_code":"logout_728x90","location_id":"9579c10f-0444-4828-a538-23af02ff5716","width":"728","height":"90"},{"inventory_code":"memcom_1260x60","location_id":"202cd25c-486d-43ce-bc0e-35e124291660","width":"1200","height":"57"},{"inventory_code":"member_728x90","location_id":"9579c10f-0444-4828-a538-23af02ff5716","width":"728","height":"90"},{"inventory_code":"talent_728x90","location_id":"9579c10f-0444-4828-a538-23af02ff5716","width":"728","height":"90"},{"inventory_code":"successHelper_728x90","location_id":"9579c10f-0444-4828-a538-23af02ff5716","width":"728","height":"90"},{"inventory_code":"companyinfo_240x90","location_id":"b374fa93-e44b-422e-bac1-f2da87ee3260","width":"240","height":"90"},{"inventory_code":"hiring_applicatns_258x136","location_id":"043b3575-153a-474a-aa2e-6a639a7d4ac1","width":"258","height":"136"},{"inventory_code":"hiring_home_main_big_894x64","location_id":"513ae9ea-18fa-4d77-8395-edcb6c337ff4","width":"894","height":"64"},{"inventory_code":"hiring_home_main_wing_160x160","location_id":"01094d82-845e-45c0-ac78-aeb2614d259a","width":"160","height":"160"},{"inventory_code":"Main-Big_543x113","location_id":"div-gpt-ad-1425521803564-0","width":"543","height":"113"},{"inventory_code":"big_1260x60","location_id":"a0bd30f0-2df2-4a6e-b802-afa8f746b539","width":"1260","height":"60"},{"inventory_code":"Main-image_230x142","location_id":"div-gpt-ad-1426837722822-0","width":"230","height":"142"},{"inventory_code":"box_300x216","location_id":"5fc011a1-5f2a-4190-8dcd-8d01d8a61382","width":"300","height":"216"},{"inventory_code":"recruit-view_250x250","location_id":"c9b4e321-23a9-4a0d-a6a8-72341ae1594f","width":"250","height":"250"},{"inventory_code":"area-list_120x600","location_id":"b05395ca-dbfd-42ab-9d44-b8bcf6092337","width":"120","height":"600"},{"inventory_code":"1000-list_120x600","location_id":"b05395ca-dbfd-42ab-9d44-b8bcf6092337\t","width":"120","height":"600"},{"inventory_code":"rapid-view_120x600","location_id":"b05395ca-dbfd-42ab-9d44-b8bcf6092337\t","width":"120","height":"600"},{"inventory_code":"etc_120x600","location_id":"b05395ca-dbfd-42ab-9d44-b8bcf6092337","width":"120","height":"600"},{"inventory_code":"CS_120x600","location_id":"b05395ca-dbfd-42ab-9d44-b8bcf6092337","width":"120","height":"600"},{"inventory_code":"category-list_120x600","location_id":"b05395ca-dbfd-42ab-9d44-b8bcf6092337","width":"120","height":"600"},{"inventory_code":"profession-list_120x600","location_id":"1a886bfa-6588-4f06-a3e0-902513b9d990","width":"120","height":"600"},{"inventory_code":"logout_120x600","location_id":"1a886bfa-6588-4f06-a3e0-902513b9d990","width":"120","height":"600"},{"inventory_code":"memcom_120x600","location_id":"1a886bfa-6588-4f06-a3e0-902513b9d990","width":"120","height":"600"},{"inventory_code":"member_120x600","location_id":"b05395ca-dbfd-42ab-9d44-b8bcf6092337","width":"120","height":"600"},{"inventory_code":"recruit-view_120x600","location_id":"b05395ca-dbfd-42ab-9d44-b8bcf6092337","width":"120","height":"600"},{"inventory_code":"talent_120x600","location_id":"b05395ca-dbfd-42ab-9d44-b8bcf6092337","width":"120","height":"600"},{"inventory_code":"etc_office_worker_in_120x600","location_id":"b05395ca-dbfd-42ab-9d44-b8bcf6092337","width":"120","height":"600"},{"inventory_code":"area-list_120x240","location_id":"div-gpt-ad-1511846653839-0","width":"120","height":"240"},{"inventory_code":"1000-list_120x240","location_id":"div-gpt-ad-1511847708022-0","width":"120","height":"240"},{"inventory_code":"etc_120x240","location_id":"div-gpt-ad-1511846339912-0","width":"120","height":"240"},{"inventory_code":"CS_120x240","location_id":"div-gpt-ad-1511845587070-0","width":"120","height":"240"},{"inventory_code":"category-list_120x240","location_id":"div-gpt-ad-1511845706684-0","width":"120","height":"240"},{"inventory_code":"profession-list_120x240","location_id":"div-gpt-ad-1511846020570-0","width":"120","height":"240"},{"inventory_code":"memcom_120x240","location_id":"div-gpt-ad-1550543155169-0","width":"120","height":"240"},{"inventory_code":"member_120x240","location_id":"div-gpt-ad-1553056482914-0","width":"120","height":"240"},{"inventory_code":"recruit-view_120x240","location_id":"div-gpt-ad-1511933728215-0","width":"120","height":"240"},{"inventory_code":"talent_120x240","location_id":"div-gpt-ad-1553056822382-0","width":"120","height":"240"},{"inventory_code":"memcom_264x264","location_id":"647bcb1c-4a55-46b3-9ea5-6d44e9e451ce","width":"264","height":"264"},{"inventory_code":"memcom_300x250","location_id":"b3151939-935a-4ae0-b218-ead990612ae2","width":"300","height":"250"},{"inventory_code":"my_right_wing_5","location_id":"eab4064a-9bec-4d9a-9f3a-9248bfe87e28","width":"267","height":"314"}]) || [];
            const resumeInfo = [];
            let targetingParams = null;
            let customTargeting = null;
            if (Object.keys(resumeInfo).length > 0) {
                targetingParams = {
                    "region": !!resumeInfo.region ? [resumeInfo.region.toString()] : [],
                    "career": !!resumeInfo.career ? [resumeInfo.career.toString()] : [],
                    "career_period": !!resumeInfo.career_period || parseInt(resumeInfo.career_period) === 0 ? [resumeInfo.career_period] : [],
                    "job": !!resumeInfo.job ? [resumeInfo.job.toString()] : [],
                }
                if (resumeInfo.custom_age) {
                    customTargeting = {"custom_age": resumeInfo.custom_age};
                }
            }

            nestads.nestAdSlotList = {};
            scriptList.forEach((row) => {
                const slot = nestads.defineSlot(row.location_id, [row.width, row.height], row.location_id);
                let config = {
                    banner: {
                        backgroundType: "CUSTOM",
                        backgroundColor: "#ffffff",
                        backgroundTransparency: 0.1,
                    }
                };
                if (row.inventory_code === 'box_300x216') {
                    config.premiumBannerVideo = {
                        expandedBannerSize: [1280, 512],
                        expandedPosition: "RIGHT_TOP",
                        autoScroll: false,
                        backgroundType: "CUSTOM",
                        backgroundColor: "#ffffff",
                        backgroundTransparency: 0.1,
                        radius: 16
                    };
                    config.banner.radius = 16
                }
                slot.setConfig(config);
                slot.addService(window.nestads.pubAds());

                // [WMG-41252] Nestads 타겟팅 파라미터 추가 // 모든 인벤토리 코드에 적용 WMG-41563
                if (targetingParams) {
                    slot.setTargeting("gender", resumeInfo.gender || 'UNKNOWN');
                    slot.setTargeting("audienceParameters", targetingParams);
                }
                if (customTargeting) {
                    slot.setTargeting("customTargeting", customTargeting);
                }

                nestads.nestAdSlotList[row.location_id] = slot;
            });

            nestads.enableServices();

            nestads.updateAdSlot = (id) => {
                if (!!!id || !!!nestads.nestAdSlotList[id]) {
                    return;
                }
                const currentSlot = nestads.nestAdSlotList[id];
                const newSlot = nestads.defineSlot(currentSlot.divId, currentSlot.size, currentSlot.placementCode);
                newSlot.addService(nestads.pubAds());
                nestads.nestAdSlotList[id] = newSlot;
                nestads.enableServices();
            };

            window.nestads.pubAds().addEventListener("slotRenderEnded", (event) => {
                if (!!event.slot) {
                    const domId = event.slot.getSlotElementId();
                    if (!!document.getElementById(domId + '-wrapper')) {
                        document.getElementById(domId + '-wrapper').querySelector('.nest-standby-banner').style.display = 'none';
                        document.getElementById(domId + '-inner').style.display = '';
                    }
                }
            });
        });
    })();
</script>
<script>
    (function(a_,i_,r_,_b,_r,_i,_d,_g,_e){if(!a_[_b]){var d={queue:[]};_r.concat(_i).forEach(function(a){var i_=a.split("."),a_=i_.pop();i_.reduce(function(a,i_){return a[i_]=a[i_]||{}},d)[a_]=function(){d.queue.push([a,arguments])}});a_[_b]=d;a_=i_.getElementsByTagName(r_)[0];i_=i_.createElement(r_);i_.onerror=function(){d.queue.filter(function(a){return 0<=_i.indexOf(a[0])}).forEach(function(a){a=a[1];a=a[a.length-1];"function"===typeof a&&a("error occur when load airbridge")})};i_.async=1;i_.src="//static.airbridge.io/sdk/latest/airbridge.min.js";a_.parentNode.insertBefore(i_,a_)}})(window,document,"script","airbridge","init fetchResource setBanner setDownload setDownloads openDeeplink setDeeplinks sendWeb setUserAgent setUserAlias addUserAlias setMobileAppData setUserId setUserEmail setUserPhone setUserAttributes clearUser setDeviceIFV setDeviceIFA setDeviceGAID events.send events.signIn events.signUp events.signOut events.purchased events.addedToCart events.productDetailsViewEvent events.homeViewEvent events.productListViewEvent events.searchResultViewEvent".split(" "),["events.wait"]);
    var airbridgeWebKey = 'ca79046f9e144d959f976fe69cdcb672';
    var appName = 'saramin';
    airbridge.init({
        app: appName,
        webToken: airbridgeWebKey,
        useProtectedAttributionWindow : true,
        utmParsing: true,
        cookieWindow: 1,
        forceFirstPartyCookieID: true
    });
    </script>
<script>

  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-12546634-1', 'saramin.co.kr');
  ga('require', 'GTM-KN35GK2');
  ga('require','displayfeatures');
  ga('require', 'linkid');
  ga('send', 'pageview');

</script></head>
<body>
<!-- skip navi -->
<div id="skipnavigation">
<a href="#sri_section">본문 바로가기</a>
</div>
<!--// skip navi -->
<header class="" id="sri_header">
<div class="wrap_header">
<a aria-label="사람인" class="bi" data-nav-track="ga_lead|section-gnb|global_menu|ci" href="/">
<span class="frame">
</span>
</a>
<div class="search">
<button class="btn_search" data-nav-track="ga_lead|section-gnb|global_menu|search" type="button">
<svg aria-hidden="true" class="icon" focusable="false"><use xlink:href="#svg_gnb_search"></use></svg>
<span class="keyword static">
                    나에게 딱 맞는 커리어만 매치, 사람인!                 </span>
<span class="keyword fixed">
                    커리어 매치, 사람인!                </span>
</button>
</div>
<div class="utility">
<div class="sign">
<a class="btn_sign signin" data-nav-track="ga_lead|section-gnb|layer_sign|signin" href="/zf_user/auth">로그인</a>
<hr/>
<a class="btn_sign signup" data-nav-track="ga_lead|section-gnb|layer_sign|join" href="/zf_user/member/registration/join">회원가입</a>
</div>
<div class="wrap_service">
<button class="btn_service" type="button">
        기업서비스
        <svg aria-hidden="true" focusable="false"><use xlink:href="#svg_gnb_profile_bracket"></use></svg>
</button>
<div class="layer_member">
<ul class="services">
<li class="half_col">
<a data-nav-track="ga_lead|section-gnb|layer_comp_service|signin_comp" href="/zf_user/auth?ut=c">로그인</a>
<a data-nav-track="ga_lead|section-gnb|layer_comp_service|company_join" href="/zf_user/member/registration/join?ut=c">회원가입</a>
</li>
<li><a data-nav-track="ga_lead|section-gnb|layer_comp_service|musthome" href="https://hiring.saramin.co.kr/home">기업홈</a></li>
<li><a data-nav-track="ga_lead|section-gnb|layer_comp_service|recruit-add" href="https://hiring.saramin.co.kr/recruit/add">공고 등록</a></li>
<li><a data-nav-track="ga_lead|section-gnb|layer_comp_service|recruit-manage" href="https://hiring.saramin.co.kr/applicant-manage">후보자 관리</a></li>
<li><a data-nav-track="ga_lead|section-gnb|layer_comp_service|talent_matching" href="/zf_user/memcom/talent-pool/main/search">인재풀</a></li>
<li><a data-nav-track="ga_lead|section-gnb|layer_comp_service|smart_recruiter" href="https://hiring.saramin.co.kr/recruit/smart">공고 요청(후불형)</a></li>
<li><a data-nav-track="ga_lead|section-gnb|layer_comp_service|verification" href="/zf_user/memcom/preview/custom-guide">인적성 · 평가도구</a></li>
<li><a data-nav-track="ga_lead|section-gnb|layer_comp_service|products" href="https://billing.saramin.co.kr/products?t_ref=main&amp;t_ref_content=member_gnb">채용상품</a></li>
<li><a data-nav-track="ga_lead|home_menu|business|" href="https://business.saramin.co.kr?utm_source=saramin&amp;utm_medium=referral&amp;utm_campaign=organic&amp;utm_content=c_drop_menu">사람인 비즈니스</a></li>
</ul>
</div>
</div>
</div>
<div class="navigation">
<button aria-expanded="false" aria-haspopup="true" class="btn_menu" data-nav-track="ga_lead|section-gnb|total_menu|open" type="button">
<svg aria-hidden="true" focusable="false"><use xlink:href="#svg_gnb_total_off"></use></svg>
<svg aria-hidden="true" focusable="false"><use xlink:href="#svg_gnb_total_on"></use></svg>
<span class="blind">전체메뉴</span>
</button>
<div class="wrap_gnb">
<div class="major recruit selected">
<a aria-current="page" class="depth1" data-nav-track="ga_lead|section-gnb|recruit|recruit" href="/zf_user/jobs/list/domestic">
<span class="txt">채용정보</span>
</a>
<ul class="depth2">
<li class="">
<a data-nav-track="ga_lead|section-gnb|recruit|area" href="/zf_user/jobs/list/domestic">
<span class="txt">지역별</span>
</a>
</li>
<li class="">
<a data-nav-track="ga_lead|section-gnb|recruit|job" href="/zf_user/jobs/list/job-category">
<span class="txt">직업별</span>
</a>
</li>
<li class="">
<a data-nav-track="ga_lead|section-gnb|recruit|area_subway" href="/zf_user/jobs/list/subway">
<span class="txt">역세권별</span>
</a>
</li>
<li class="selected">
<a data-nav-track="ga_lead|section-gnb|recruit|hot100" href="/zf_user/jobs/hot100">
<span class="txt">HOT100</span>
</a>
</li>
<li class="">
<a data-nav-track="ga_lead|section-gnb|recruit|headhunting" href="/zf_user/jobs/list/headhunting">
<span class="txt">헤드헌팅</span>
</a>
</li>
<li class="">
<a data-nav-track="ga_lead|section-gnb|recruit|theme" href="/zf_user/jobs/theme/main">
<span class="txt">채용관</span>
</a>
</li>
<li class="">
<a data-nav-track="ga_lead|section-gnb|recruit|curation" href="/zf_user/curation">
<span class="txt">큐레이션</span>
</a>
</li>
<li class="">
<a data-nav-track="ga_lead|section-gnb|recruit|dispatch" href="/zf_user/jobs/list/dispatch">
<span class="txt">파견대행</span>
</a>
</li>
<li class="">
<a data-nav-track="ga_lead|section-gnb|recruit|komate" href="https://komate.saramin.co.kr" target="_blank">
<span class="txt">외국인 채용</span>
</a>
</li>
<li class="">

## 회사명

In [284]:
# 1. 부모 태그와 선택자로 넓은 범위에서 접근 < .. ?????????????????
                        # 태그.클래스명     .클래스명
company = soup.select('div.col.company_nm .str_tit') # 태그가 각각 a, span이어서 문제였는데.. 클래스 이름이 str_tit으로 같아서 태그 생략하고 넣음
company
print(len(company))

company_list = []

for i in range(1, len(company)):
    company_list.append(company[i].text.strip())
print(company_list)

11
['(주)엘티엔터테인먼트', '현대종합금속(주)', '(주)인투알', '(주)더블티', '한화에어로스페이스(주)', '에스케이바이오사이언스(주)', '앰코테크놀로지코리아㈜', '미창석유공업(주)', '쿠쿠홀딩스(주)', '충남콘텐츠진흥원(재)']

In [276]:
# 2. 원하는 태그에 각각 접근하기
# 여러 태그가 복잡하게 얽혀 있을 경우, 조건문으로 상황에 맞게 태그 값을 지정해서 정보를 가져오기
c_list = []

for i in company:
    # a 태그에 값이 있다면, True로 인지함!
    target = i.select('a') or i.select('span')
        # select로 해도 되지만 리스트로 반환 받으므로 한 번 더 정제해야 하는데
        # select_one은 하나의 값만 반환해서 편하게 사용 가능
        # 어차피 우리가 원하는 회사명은 단일 값이므로 select_one으로 받는 게 더 효율적
        # target = i.select_one('a')
        
    # a 태그에 값이 없다면 span 태그를 확인    
    # elif i.select('span'):
        # target = i.select_one('span')
        
    if target:
        c_list.append(target.text.strip())
c_list

[]

## 공고명

In [253]:
title = soup.select('a.str_tit > span')
title[2].text

title_list = []

for i in range(1, len(title)):
    title_list.append(title[i].text.strip())
print(title_list)

['제주 드림타워 복합리조트 [카지노&호텔] 대규모 신입/경력 공채', '신입/경력 사원 모집', '[사세확장] 각 부서별 정규직 채용', '2026년 전직군 신입/경력 채용', '2026년 상반기 항공사업부 전문직 채용전제형 인턴 채용', '26년 1월 신입/경력사원 수시채용', '[신입] 제조직(Operator) 정규직 모집 (인천 송도, 부평)', '상반기 신입사원 채용 공고', '쿠쿠전자㈜ 생산직 사원 경력무관 채용', '2026년 제1차 정규직 직원채용 공고']

## 근무지역

In [203]:
region = soup.select('p.work_place')
region[2].text

region_list = []
for i in range(1, len(region)):
    region_list.append(region[i].text.strip())
print(region_list)

['제주 제주시 외', '서울 강남구', '경기 김포시 외', '경기 수원시 권선구 외', '충남 아산시', '인천 연수구', '인천 연수구 외', '부산 영도구 외', '경남 양산시 외', '충남 아산시 외']

## 경력

In [202]:
career = soup.select('p.career')
career[2].text

career_list = []
for i in range(1, len(career)):
    career_list.append(career[i].text.strip())
print(career_list)

['신입 · 정규직 외', '신입 · 정규직', '경력무관 · 정규직', '경력무관 · 정규직 외', '신입 · 정규직 외', '경력무관 · 정규직', '신입 · 정규직', '신입 · 정규직', '경력무관 · 정규직', '신입 · 정규직']

## 학력

In [200]:
education = soup.select('p.education')
education[2].text

print(len(education))

edu_list = []
for i in range(1, len(education)):
    edu_list.append(education[i].text.strip())
print(edu_list)

11
['학력무관', '대학교(4년)↑', '학력무관', '대학(2,3년)↑', '대학(2,3년)↑', '대학교(4년)↑', '고졸↑', '대학(2,3년)↑', '고졸↑', '학력무관']

In [266]:
saramin = {'회사명':company_list,
'공고명':title_list,
'근무지역':region_list,
'경력':career_list,
'학력':edu_list}

saramin

{'회사명': ['(주)엘티엔터테인먼트',
  '현대종합금속(주)',
  '(주)인투알',
  '(주)더블티',
  '한화에어로스페이스(주)',
  '에스케이바이오사이언스(주)',
  '앰코테크놀로지코리아㈜',
  '미창석유공업(주)',
  '쿠쿠홀딩스(주)',
  '충남콘텐츠진흥원(재)'],
 '공고명': ['제주 드림타워 복합리조트 [카지노&호텔] 대규모 신입/경력 공채',
  '신입/경력 사원 모집',
  '[사세확장] 각 부서별 정규직 채용',
  '2026년 전직군 신입/경력 채용',
  '2026년 상반기 항공사업부 전문직 채용전제형 인턴 채용',
  '26년 1월 신입/경력사원 수시채용',
  '[신입] 제조직(Operator) 정규직 모집 (인천 송도, 부평)',
  '상반기 신입사원 채용 공고',
  '쿠쿠전자㈜ 생산직 사원 경력무관 채용',
  '2026년 제1차 정규직 직원채용 공고'],
 '근무지역': ['제주 제주시 외',
  '서울 강남구',
  '경기 김포시 외',
  '경기 수원시 권선구 외',
  '충남 아산시',
  '인천 연수구',
  '인천 연수구 외',
  '부산 영도구 외',
  '경남 양산시 외',
  '충남 아산시 외'],
 '경력': ['신입 · 정규직 외',
  '신입 · 정규직',
  '경력무관 · 정규직',
  '경력무관 · 정규직 외',
  '신입 · 정규직 외',
  '경력무관 · 정규직',
  '신입 · 정규직',
  '신입 · 정규직',
  '경력무관 · 정규직',
  '신입 · 정규직'],
 '학력': ['학력무관',
  '대학교(4년)↑',
  '학력무관',
  '대학(2,3년)↑',
  '대학(2,3년)↑',
  '대학교(4년)↑',
  '고졸↑',
  '대학(2,3년)↑',
  '고졸↑',
  '학력무관']}

In [280]:
df = pd.DataFrame(saramin, index=range(1, 11))
df.index.name = '순위'
df

,회사명,공고명,근무지역,경력,학력
순위,,,,,
1,(주)엘티엔터테인먼트,제주 드림타워 복합리조트 [카지노&호텔] 대규모 신입/경력 공채,제주 제주시 외,신입 · 정규직 외,학력무관
2,현대종합금속(주),신입/경력 사원 모집,서울 강남구,신입 · 정규직,대학교(4년)↑
3,(주)인투알,[사세확장] 각 부서별 정규직 채용,경기 김포시 외,경력무관 · 정규직,학력무관
4,(주)더블티,2026년 전직군 신입/경력 채용,경기 수원시 권선구 외,경력무관 · 정규직 외,"대학(2,3년)↑"
5,한화에어로스페이스(주),2026년 상반기 항공사업부 전문직 채용전제형 인턴 채용,충남 아산시,신입 · 정규직 외,"대학(2,3년)↑"
6,에스케이바이오사이언스(주),26년 1월 신입/경력사원 수시채용,인천 연수구,경력무관 · 정규직,대학교(4년)↑
7,앰코테크놀로지코리아㈜,"[신입] 제조직(Operator) 정규직 모집 (인천 송도, 부평)",인천 연수구 외,신입 · 정규직,고졸↑
8,미창석유공업(주),상반기 신입사원 채용 공고,부산 영도구 외,신입 · 정규직,"대학(2,3년)↑"
9,쿠쿠홀딩스(주),쿠쿠전자㈜ 생산직 사원 경력무관 채용,경남 양산시 외,경력무관 · 정규직,고졸↑
10,충남콘텐츠진흥원(재),2026년 제1차 정규직 직원채용 공고,충남 아산시 외,신입 · 정규직,학력무관

In [281]:
df.to_csv("사람인 공고 10.csv", encoding='utf-8')

# 네이버페이 증권 데이터 크롤링 하기
- 세계 각국의 통화명과 매매기준율 크롤링~!

In [307]:
res = requests.get("https://finance.naver.com/marketindex/", headers=U_A)
soup = bs(res.text, 'lxml')
soup

<html><head><script language="javascript" src="/template/head_js.naver?referer=info.finance.naver.com&amp;menu=marketindex&amp;submenu=market"></script>
<script src="https://ssl.pstatic.net/imgstock/static.pc/20260121140926/js/info/jindo.min.ns.1.5.3.euckr.js" type="text/javascript"></script>
<script src="https://ssl.pstatic.net/imgstock/static.pc/20260121140926/js/jindo.1.5.3.element-text-patch.js" type="text/javascript"></script>
</head><body><div id="container" style="padding-bottom:0px;">
<div class="market_include">
<div class="market_data">
<div class="market1">
<div class="title">
<h2 class="h_market1"><span>환전 고시 환율</span></h2>
</div>
<!-- data -->
<div class="data">
<ul class="data_lst" id="exchangeList">
<li class="on">
<a class="head usd" href="/marketindex/exchangeDetail.naver?marketindexCd=FX_USDKRW" onclick="clickcr(this, 'fr1.usdt', '', '', event);">
<h3 class="h_lst"><span class="blind">미국 USD</span></h3>
<div class="head_info point_dn">
<span class="value">1,471.50</span>
<span class="txt_krw"><span class="blind">원</span></span>
<span class="change"> 8.30</span>
<span class="blind">하락</span>
</div>
</a>
<a class="graph_img" href="/marketindex/exchangeDetail.naver?marketindexCd=FX_USDKRW" onclick="clickcr(this, 'fr1.usdc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_USDKRW.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2026.01.21 15:42</span>
<span class="source">하나은행 기준</span>
<span class="count">고시회차<span class="num">446</span>회</span>
</div>
</li>
<li class="">
<a class="head jpy" href="/marketindex/exchangeDetail.naver?marketindexCd=FX_JPYKRW" onclick="clickcr(this, 'fr1.jpyt', '', '', event);">
<h3 class="h_lst"><span class="blind">일본 JPY(100엔)</span></h3>
<div class="head_info point_dn">
<span class="value">930.71</span>
<span class="txt_krw"><span class="blind">원</span></span>
<span class="change"> 4.66</span>
<span class="blind">하락</span>
</div>
</a>
<a class="graph_img" href="/marketindex/exchangeDetail.naver?marketindexCd=FX_JPYKRW" onclick="clickcr(this, 'fr1.jpyc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_JPYKRW.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2026.01.21 15:42</span>
<span class="source">하나은행 기준</span>
<span class="count">고시회차<span class="num">446</span>회</span>
</div>
</li>
<li class="">
<a class="head eur" href="/marketindex/exchangeDetail.naver?marketindexCd=FX_EURKRW" onclick="clickcr(this, 'fr1.eurt', '', '', event);">
<h3 class="h_lst"><span class="blind">유럽연합 EUR</span></h3>
<div class="head_info point_dn">
<span class="value">1,724.97</span>
<span class="txt_krw"><span class="blind">원</span></span>
<span class="change"> 9.21</span>
<span class="blind">하락</span>
</div>
</a>
<a class="graph_img" href="/marketindex/exchangeDetail.naver?marketindexCd=FX_EURKRW" onclick="clickcr(this, 'fr1.eurc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_EURKRW.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2026.01.21 15:42</span>
<span class="source">하나은행 기준</span>
<span class="count">고시회차<span class="num">446</span>회</span>
</div>
</li>
<li class="">
<a class="head cny" href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CNYKRW" onclick="clickcr(this, 'fr1.cnyt', '', '', event);">
<h3 class="h_lst"><span class="blind">중국 CNY</span></h3>
<div class="head_info point_dn">
<span class="value">211.39</span>
<span class="txt_krw"><span class="blind">원</span></span>
<span class="change"> 1.33</span>
<span class="blind">하락</span>
</div>
</a>
<a class="graph_img" href="/marketindex/exchangeDetail.naver?marketindexCd=FX_CNYKRW" onclick="clickcr(this, 'fr1.cnyc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_CNYKRW.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2026.01.21 15:42</span>
<span class="source">하나은행 기준</span>
<span class="count">고시회차<span class="num">446</span>회</span>
</div>
</li>
</ul>
</div>
<!-- //data -->
</div>
<div class="market2">
<div class="title">
<h2 class="h_market2"><span>국제 시장 환율</span></h2>
</div>
<!-- data -->
<div class="data">
<ul class="data_lst" id="worldExchangeList">
<li class="on">
<a class="head jpy_usd" href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_USDJPY" onclick="clickcr(this, 'fr2.jpyut', '', '', event);">
<h3 class="h_lst"><span class="blind">달러/일본 엔</span></h3>
<div class="head_info point_up">
<span class="value">158.0600</span>
<span class="txt_jpy"><span class="blind">엔</span></span>
<span class="change">0.1600</span>
<span class="blind">상승</span>
</div>
</a>
<a class="graph_img" href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_USDJPY" onclick="clickcr(this, 'fr2.jpyuc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_USDJPY.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2026.01.20</span>
<span class="source">모닝스타 기준</span>
</div>
</li>
<li class="">
<a class="head usd_eur" href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_EURUSD" onclick="clickcr(this, 'fr2.eurdt', '', '', event);">
<h3 class="h_lst"><span class="blind">유로/달러</span></h3>
<div class="head_info point_up">
<span class="value">1.1717</span>
<span class="txt_usd"><span class="blind">달러</span></span>
<span class="change">0.0077</span>
<span class="blind">상승</span>
</div>
</a>
<a class="graph_img" href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_EURUSD" onclick="clickcr(this, 'fr2.eurdc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_EURUSD.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2026.01.20</span>
<span class="source">모닝스타 기준</span>
</div>
</li>
<li class="">
<a class="head usd_gbp" href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_GBPUSD" onclick="clickcr(this, 'fr2.gbpdt', '', '', event);">
<h3 class="h_lst"><span class="blind">영국 파운드/달러</span></h3>
<div class="head_info point_up">
<span class="value">1.3452</span>
<span class="txt_usd"><span class="blind">달러</span></span>
<span class="change">0.0032</span>
<span class="blind">상승</span>
</div>
</a>
<a class="graph_img" href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_GBPUSD" onclick="clickcr(this, 'fr2.gbpdc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_GBPUSD.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2026.01.20</span>
<span class="source">모닝스타 기준</span>
</div>
</li>
<li class="">
<a class="head usd_idx" href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_USDX" onclick="clickcr(this, 'fr2.indt', '', '', event);">
<h3 class="h_lst"><span class="blind">달러인덱스</span></h3>
<div class="head_info point_dn">
<span class="value">98.4300</span>
<span class="change"> 0.7700</span>
<span class="blind">하락</span>
</div>
</a>
<a class="graph_img" href="/marketindex/worldExchangeDetail.naver?marketindexCd=FX_USDX" onclick="clickcr(this, 'fr2.indc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/FX_USDX.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2026.01.20</span>
<span class="source">ICE 기준</span>
</div>
</li>
</ul>
</div>
<!-- //data -->
</div>
<div class="market3">
<div class="title">
<h2 class="h_market3"><span>유가·금시세</span></h2>
</div>
<!-- data -->
<div class="data">
<ul class="data_lst" id="oilGoldList">
<li class="on">
<a class="head wti" href="/marketindex/worldOilDetail.naver?marketindexCd=OIL_CL&amp;fdtc=2" onclick="clickcr(this, 'fr3.wtit', '', '', event);">
<h3 class="h_lst"><span class="blind">WTI</span></h3>
<div class="head_info point_up">
<span class="value">60.36</span>
<span class="txt_usd"><span class="blind">달러</span></span>
<span class="change">1.02</span>
<span class="blind">상승</span>
</div>
</a>
<a class="graph_img" href="/marketindex/worldOilDetail.naver?marketindexCd=OIL_CL&amp;fdtc=2" onclick="clickcr(this, 'fr3.wtic', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/OIL_CL.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2026.01.20</span>
<span class="source">NYMEX(뉴욕상업거래소) 기준</span>
</div>
</li>
<li class="">
<a class="head gasoline" href="/marketindex/oilDetail.naver?marketindexCd=OIL_GSL" onclick="clickcr(this, 'fr3.oilt', '', '', event);">
<h3 class="h_lst"><span class="blind">휘발유</span></h3>
<div class="head_info point_dn">
<span class="value">1695.02</span>
<span class="txt_krw"><span class="blind">원</span></span>
<span class="change"> 1.18</span>
<span class="blind">하락</span>
</div>
</a>
<a class="graph_img" href="/marketindex/oilDetail.naver?marketindexCd=OIL_GSL" onclick="clickcr(this, 'fr3.oilc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/OIL_GSL.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2026.01.21</span>
<span class="source">한국석유공사 Opinet 기준</span>
</div>
</li>
<li class="">
<a class="head gold_inter" href="/marketindex/worldGoldDetail.naver?marketindexCd=CMDT_GC&amp;fdtc=2" onclick="clickcr(this, 'fr3.agoldt', '', '', event);">
<h3 class="h_lst"><span class="blind">국제 금</span></h3>
<div class="head_info point_up">
<span class="value">4765.8</span>
<span class="txt_usd"><span class="blind">달러</span></span>
<span class="change">170.40</span>
<span class="blind">상승</span>
</div>
</a>
<a class="graph_img" href="/marketindex/worldGoldDetail.naver?marketindexCd=CMDT_GC&amp;fdtc=2" onclick="clickcr(this, 'fr3.agoldc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/CMDT_GC.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2026.01.20</span>
<span class="source">COMEX(뉴욕상품거래소) 기준</span>
</div>
</li>
<li class="">
<a class="head gold_domestic" href="/marketindex/goldDetail.naver" onclick="clickcr(this, 'fr3.kgoldt', '', '', event);">
<h3 class="h_lst"><span class="blind">국내 금</span></h3>
<div class="head_info point_up">
<span class="value">230847.95</span>
<span class="txt_krw"><span class="blind">원</span></span>
<span class="change">5,007.35</span>
<span class="blind">상승</span>
</div>
</a>
<a class="graph_img" href="/marketindex/goldDetail.naver" onclick="clickcr(this, 'fr3.kgoldc', '', '', event);">
<img alt="" height="153" src="https://ssl.pstatic.net/imgfinance/chart/marketindex/CMDT_GD.png" width="295"/>
</a>
<div class="graph_info">
<span class="time">2026.01.21 15:37</span>
<span class="source">신한은행 기준</span>
							(<span class="num">375</span>회차)
					</div>
</li>
</ul>
</div>
<!-- //data -->
</div>
</div>
</div>
<div class="marketindex_content _replaceNewsLink" id="content">
<div class="section_news">
<h3 class="h_market"><span>환율 주요뉴스</span></h3>
<div class="list_area">
<ul>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D&amp;section_id=101&amp;section_id2=258&amp;section_id3=429&amp;office_id=277&amp;article_id=0005709987" onclick="clickcr(this, 'mhn.list', '277_0005709987', '0', event);">원·달러 환율 6.8원 내린 1471.3원</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>01.21 15:33</span>
</li>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D&amp;section_id=101&amp;section_id2=258&amp;section_id3=429&amp;office_id=001&amp;article_id=0015859269" onclick="clickcr(this, 'mhn.list', '001_0015859269', '1', event);">외환건전성 부담금 한시면제…금융사 '서민금</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>01.21 15:00</span>
</li>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D&amp;section_id=101&amp;section_id2=258&amp;section_id3=429&amp;office_id=001&amp;article_id=0015858732" onclick="clickcr(this, 'mhn.list', '001_0015858732', '2', event);">지난해 발견된 위조지폐 98장…33% 감소</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>01.21 12:00</span>
</li>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D&amp;section_id=101&amp;section_id2=258&amp;section_id3=429&amp;office_id=422&amp;article_id=0000825071" onclick="clickcr(this, 'mhn.list', '422_0000825071', '3', event);">이대통령 '환율 하락' 언급에…1,460원</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>01.21 11:10</span>
</li>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D&amp;section_id=101&amp;section_id2=258&amp;section_id3=429&amp;office_id=422&amp;article_id=0000825065" onclick="clickcr(this, 'mhn.list', '422_0000825065', '4', event);">이 대통령 "당국, 환율 한두 달 뒤 1,</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>01.21 10:58</span>
</li>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D&amp;section_id=101&amp;section_id2=258&amp;section_id3=429&amp;office_id=001&amp;article_id=0015858468" onclick="clickcr(this, 'mhn.list', '001_0015858468', '5', event);">이대통령 '환율 하락' 언급에…1,460원</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>01.21 10:56</span>
</li>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D&amp;section_id=101&amp;section_id2=258&amp;section_id3=429&amp;office_id=001&amp;article_id=0015858344" onclick="clickcr(this, 'mhn.list', '001_0015858344', '6', event);">李대통령 "당국, 환율 한두 달 뒤 1천4</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>01.21 10:36</span>
</li>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D&amp;section_id=101&amp;section_id2=258&amp;section_id3=429&amp;office_id=277&amp;article_id=0005709754" onclick="clickcr(this, 'mhn.list', '277_0005709754', '7', event);">그린란드 무역긴장, '셀 아메리카' 우려↑</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>01.21 10:27</span>
</li>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D&amp;section_id=101&amp;section_id2=258&amp;section_id3=429&amp;office_id=001&amp;article_id=0015858272" onclick="clickcr(this, 'mhn.list', '001_0015858272', '8', event);">[속보] 李대통령 "당국, 환율 1∼2달 </a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>01.21 10:24</span>
</li>
<li>
<p><a href="/news/news_read.naver?mode=LSS3D&amp;section_id=101&amp;section_id2=258&amp;section_id3=429&amp;office_id=015&amp;article_id=0005240099" onclick="clickcr(this, 'mhn.list', '015_0005240099', '9', event);">원·달러 환율, 한 달 만에 장중 1480</a><img alt="NEW" height="8" src="https://ssl.pstatic.net/static/nfinance/ico_new.gif" width="8"/></p>
<span>01.21 10:20</span>
</li>
</ul>
</div>
<a class="btn_more" href="/news/news_list.naver?mode=LSS3D&amp;section_id=101&amp;section_id2=258&amp;section_id3=429" onclick="clickcr(this, 'mhn.more', '', '', event);"><img alt="더보기" height="18" src="https://ssl.pstatic.net/static/nfinance/btn_more.gif" width="34"/></a>
</div>
<div class="tab_default1" id="tab_section">
<ul>
<li class="on"><a href="./?tabSel=exchange#tab_section" onclick="clickcr(this, 'mtb.exnoti', '', '', event);"><span class="tab1">환전고시 환율</span></a></li>
<li class=""><a href="./?tabSel=worldExchange#tab_section" onclick="clickcr(this, 'mtb.interex', '', '', event);"><span class="tab2">국제시장 환율</span></a></li>
<li class=""><a href="./?tabSel=gold#tab_section" onclick="clickcr(this, 'mtb.oilgold', '', '', event);"><span class="tab3">유가 금시세</span></a></li>
<li class=""><a href="./?tabSel=materials#tab_section" onclick="clickcr(this, 'mtb.material', '', '', event);"><span class="tab4">원자재</span></a></li>
</ul>
<h2 class="blind">환전고시 환율</h2>
</div>
<div class="section_calculator">
<h3 class="h_calculator"><span>환율계산기 (매매기준율 기준)</span></h3>
<div class="calculator">
<div class="inner">
<div class="input">
<div class="selectbox-noscript" id="sInput">
<select class="selectbox-source" id="select_from">
<option label="1" value="1">대한민국 원 KRW</option>
<option class="selectbox-default" label="1" selected="selected" value="1471.5"> 미국 달러 USD</option>
<option label="1" value="1471.5"> 미국 달러 USD</option>
<option label="1" value="1724.97"> 유럽연합 유로 EUR</option>
<option label="100" value="9.3071"> 일본 엔 JPY</option>
<option label="1" value="211.39"> 중국 위안 CNY</option>
<option label="1" value="188.71"> 홍콩 달러 HKD</option>
<option label="1" value="46.51"> 대만 달러 TWD</option>
<option label="1" value="1977.77"> 영국 파운드 GBP</option>
<option label="1" value="3822.28"> 오만 리알 OMR</option>
<option label="1" value="1063.8"> 캐나다 달러 CAD</option>
<option label="1" value="1860.89"> 스위스 프랑 CHF</option>
<option label="1" value="161.42"> 스웨덴 크로나 SEK</option>
<option label="1" value="992.45"> 호주 달러 AUD</option>
<option label="1" value="860.02"> 뉴질랜드 달러 NZD</option>
<option label="1" value="70.88"> 체코 코루나 CZK</option>
<option label="1" value="1.66"> 칠레 페소 CLP</option>
<option label="1" value="33.99"> 튀르키예 뉴리라 TRY</option>
<option label="1" value="0.41"> 몽골 투그릭 MNT</option>
<option label="1" value="464.63"> 이스라엘 세켈 ILS</option>
<option label="1" value="230.91"> 덴마크 크로네 DKK</option>
<option label="1" value="147.4"> 노르웨이 크로네 NOK</option>
<option label="1" value="392.4"> 사우디아라비아 리얄 SAR</option>
<option label="1" value="4815.91"> 쿠웨이트 디나르 KWD</option>
<option label="1" value="3902.87"> 바레인 디나르 BHD</option>
<option label="1" value="400.66"> 아랍에미리트 디르함 AED</option>
<option label="1" value="2075.46"> 요르단 디나르 JOD</option>
<option label="1" value="30.97"> 이집트 파운드 EGP</option>
<option label="1" value="47.25"> 태국 바트 THB</option>
<option label="1" value="1146.3"> 싱가포르 달러 SGD</option>
<option label="1" value="362.84"> 말레이시아 링깃 MYR</option>
<option label="100" value="0.0868"> 인도네시아 루피아 IDR</option>
<option label="1" value="402.6"> 카타르 리얄 QAR</option>
<option label="1" value="2.9"> 카자흐스탄 텡게 KZT</option>
<option label="1" value="1146.3"> 브루나이 달러 BND</option>
<option label="1" value="16.07"> 인도 루피 INR</option>
<option label="1" value="5.26"> 파키스탄 루피 PKR</option>
<option label="1" value="12.03"> 방글라데시 타카 BDT</option>
<option label="1" value="24.82"> 필리핀 페소 PHP</option>
<option label="1" value="83.7"> 멕시코 페소 MXN</option>
<option label="1" value="273.72"> 브라질 레알 BRL</option>
<option label="100" value="0.056100000000000004"> 베트남 동 VND</option>
<option label="1" value="89.86"> 남아프리카 공화국 랜드 ZAR</option>
<option label="1" value="18.91"> 러시아 루블 RUB</option>
<option label="1" value="4.48"> 헝가리 포린트 HUF</option>
<option label="1" value="408.38"> 폴란드 즈워티 PLN</option>
<option label="1" value="4.75"> 스리랑카 루피 LKR</option>
<option label="1" value="11.34"> 알제리 알제리 디나르 DZD</option>
<option label="1" value="11.41"> 케냐 실링 KES</option>
<option label="1" value="0.4"> 콜롬비아 페소 COP</option>
<option label="1" value="0.58"> 탄자니아 실링 TZS</option>
<option label="1" value="10.05"> 네팔 루피 NPR</option>
<option label="1" value="338.7"> 루마니아 레우 RON</option>
<option label="1" value="231.17"> 리비아 리비아 디나르 LYD</option>
<option label="1" value="183.14"> 마카오 파타카 MOP</option>
<option label="1" value="0.7"> 미얀마 짯 MMK</option>
<option label="1" value="9.45"> 에티오피아 비르 ETB</option>
<option label="1" value="0.12"> 우즈베키스탄 숨 UZS</option>
<option label="1" value="0.37"> 캄보디아 리엘 KHR</option>
<option label="1" value="648.93"> 피지 피지 달러 FJD</option>
</select>
<div class="selectbox-box" onclick="clickcr(this, 'exl*c.clist1', '', '', event);">
<div class="selectbox-label"></div>
</div>
<div class="selectbox-layer ly_calculator">
<div class="selectbox-list"></div>
</div>
</div>
<div class="input_area" id="input_from">
<input id="input_from_money" maxlength="10" onclick="clickcr(this, 'exl*c.unit1', '', '', event);" onfocus="changeActiveInput('from', 'to'); return false;" onkeyup="calcExchange('from', 'to', 'on', event);" type="text" value="1"/>

## iframe 태그
- **다른 서버의 웹 페이지 데이터나 리소스를 현재 서버의 웹 페이지에 포함**시켜 보여주는 HTML 태그
- 웹페이지에 보여줄 데이터가 많은 경우 한번에 접근하려면 그만큼 속도가 느려질 수 있는데, 이를 방지하거나 데이터를 따로 관리하기 용이하게 하기 위해 iframe 태그를 사용함!
- 우리가 수집하길 원하는 정보가 iframe 태그 내에 있다면, 기존 url로는 접근이 불가하고, 해당 데이터가 있는 원천 서버주소로 접근해야 함! (원하는 정보의 태그를 포함하는 내부 전체 \<HTML> 태그를 찾고 그 바로 위에 iframe 태그가 존재함 )

In [308]:
# iframe 태그의 정보가 있는 원천 서버로 다시 통신 요청
res = requests.get("https://finance.naver.com/marketindex/exchangeList.naver", headers=U_A)
soup = bs(res.text, 'lxml')

In [311]:
nation = soup.select('td.tit > a')
nation[0].text

'\n\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t\t\n\t\t\t\t\t미국 USD\n\t\t\t\t\n\t\t\t\t'

In [319]:
base = soup.select('td.sale')
base[0].text

len(base)

base_list, nation_list = [], []

for i in range(len(base)):
    base_list.append(base[i].text.strip()+'원')
    nation_list.append(nation[i].text.strip())

In [326]:
dic = {'통화명': nation_list,
      '매매기준율': base_list}

df = pd.DataFrame(dic, index=range(1,59))
df.index.name = 'No'
df

              통화명      매매기준율
No
1          미국 USD  1,471.50원
2        유럽연합 EUR  1,724.97원
3   일본 JPY (100엔)    930.71원
4          중국 CNY    211.39원
5          홍콩 HKD    188.71원
6          대만 TWD     46.51원
7          영국 GBP  1,977.77원
8          오만 OMR  3,822.28원
9         캐나다 CAD  1,063.80원
10        스위스 CHF  1,860.89원
11        스웨덴 SEK    161.42원
12         호주 AUD    992.45원
13       뉴질랜드 NZD    860.02원
14         체코 CZK     70.88원
15         칠레 CLP      1.66원
16       튀르키예 TRY     33.99원
17         몽골 MNT      0.41원
18       이스라엘 ILS    464.63원
19        덴마크 DKK    230.91원
20       노르웨이 NOK    147.40원
21    사우디아라비아 SAR    392.40원
22       쿠웨이트 KWD  4,815.91원
23        바레인 BHD  3,902.87원
24     아랍에미리트 AED    400.66원
25        요르단 JOD  2,075.46원
26        이집트 EGP     30.97원
27         태국 THB     47.25원
28       싱가포르 SGD  1,146.30원
29      말레이시아 MYR    362.84원
30  인도네시아 IDR 100      8.68원
31        카타르 QAR    402.60원
32      카자흐스탄 KZT      2.90원
33       브루나이 BND  1,146.30원
34         인도 INR     16.07원
35       파키스탄 PKR      5.26원
36      방글라데시 BDT     12.03원
37        필리핀 PHP     24.82원
38        멕시코 MXN     83.70원
39        브라질 BRL    273.72원
40    베트남 VND 100      5.61원
41  남아프리카 공화국 ZAR     89.86원
42        러시아 RUB     18.91원
43        헝가리 HUF      4.48원
44        폴란드 PLN    408.38원
45       스리랑카 LKR      4.75원
46        알제리 DZD     11.34원
47         케냐 KES     11.41원
48       콜롬비아 COP      0.40원
49       탄자니아 TZS      0.58원
50         네팔 NPR     10.05원
51       루마니아 RON    338.70원
52        리비아 LYD    231.17원
53        마카오 MOP    183.14원
54        미얀마 MMK      0.70원
55      에티오피아 ETB      9.45원
56     우즈베키스탄 UZS      0.12원
57       캄보디아 KHR      0.37원
58         피지 FJD    648.93원

# 만개의 레시피 데이터 크롤링
- 레시피명, 작성자, 조회수 크롤링~!

In [330]:
res = requests.get("https://www.10000recipe.com/recipe/list.html", headers=U_A)
soup = bs(res.text, 'lxml')
soup

<!DOCTYPE html>
<!--[if (IE 6)|(IE 7)|(IE 8)|(IE 9)]>
<html lang="ko" xmlns="http://www.w3.org/1999/xhtml" class="old_ie">
<![endif]-->
<html class="" lang="ko" xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<meta content="IE=Edge" http-equiv="X-UA-Compatible"/>
<meta content="no-cache" http-equiv="Pragma"/>
<meta content="-1" http-equiv="Expires"/>
<link href="/manifest.json" rel="manifest"/>
<meta content="1567451316868458" property="fb:pages"/>
<meta content="국내 No.1 요리앱, 10만개 이상의 레시피, 편리한 검색, 맛보장 레시피, TV쿡방 레시피, 온라인 최저가 쇼핑, 요리 공모전" name="description"/>
<meta content="" name="keywords"/>
<meta content="3eLg1zfxeZ_oO6oOOsvIxbtcW-FtDsViPVm7-CYOl8w" name="google-site-verification"/>
<meta content="1f5cc8d2183836842bd3db03bc960620" name="p:domain_verify"/>
<meta content="" name="user_id"/>
<title>요리를 즐겁게~ 만개의레시피</title>
<meta content="요리를 즐겁게~ 만개의레시피" property="kakao:title"/>
<meta content="" property="kakao:description"/>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-PDPW2LX');</script>
<link href="https://recipe1.ezmember.co.kr/static/css/bootstrap_20211222.css" rel="stylesheet" type="text/css"/>
<link href="https://recipe1.ezmember.co.kr/static/css/font_20230910.css" rel="stylesheet" type="text/css"/>
<link href="https://recipe1.ezmember.co.kr/static/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
<link href="https://recipe1.ezmember.co.kr/static/css/ez_recipe_20250928.css" rel="stylesheet" type="text/css"/>
<link href="https://www.10000recipe.com/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
<link href="https://recipe1.ezmember.co.kr/img/icons/apple-touch-icon.png" rel="apple-touch-icon"/>
<link href="https://recipe1.ezmember.co.kr/img/icons/apple-touch-icon-76x76.png" rel="apple-touch-icon" sizes="76x76"/>
<link href="https://recipe1.ezmember.co.kr/img/icons/apple-touch-icon-120x120.png" rel="apple-touch-icon" sizes="120x120"/>
<link href="https://recipe1.ezmember.co.kr/img/icons/apple-touch-icon-152x152.png" rel="apple-touch-icon" sizes="152x152"/>
<link href="https://recipe1.ezmember.co.kr/img/icons/apple-touch-icon-180x180.png" rel="apple-touch-icon" sizes="180x180"/>
<link href="https://recipe1.ezmember.co.kr/img/icons/icon-hires.png" rel="icon" sizes="192x192"/>
<link href="https://recipe1.ezmember.co.kr/img/icons/icon-normal.png" rel="icon" sizes="128x128"/>
<script charset="utf-8" src="https://recipe1.ezmember.co.kr/static/js/jquery-1.11.2.min.js" type="text/javascript"></script>
<script src="//static.criteo.net/js/ld/publishertag.js" type="text/javascript"></script>
<script type="text/javascript">
// Common Javascript
var _WWW_URL_ = 'https://www.10000recipe.com';
var _IMG_URL_ = 'https://recipe1.ezmember.co.kr';
var _FILE_URL_ = 'https://recipe1.ezmember.co.kr/cache';
var _CURRENT_PAGE_ = 'https://www.10000recipe.com/recipe/list.html';
var _USER_ID_ = '';
</script>
<script async="" src="https://securepubads.g.doubleclick.net/tag/js/gpt.js"></script>
<script>
  window.googletag = window.googletag || {cmd: []};
  googletag.cmd.push(function() {
    googletag.defineSlot('/21842705582/10k_w_recipe_top', [[970, 90], [728, 90]], 'div-gpt-ad-1576827715543-0').addService(googletag.pubads());
    googletag.pubads().enableSingleRequest();
    googletag.pubads().collapseEmptyDivs();
    googletag.enableServices();
  });
</script>
<script type="text/javascript">
function showInfoSourcing() {
    EAD.showDialog({'title':'상품 연결 안내','url':'/recipe/info_sourcing.html','width':1020,'modal':true});
}
</script>
<!-- LOGGER(TM) TRACKING SCRIPT V.40 FOR logger.co.kr / 39580 : COMBINE TYPE / DO NOT ALTER THIS SCRIPT. -->
<script type="text/javascript">var _TRK_LID="39580";var _L_TD="ssl.logger.co.kr";var _TRK_CDMN="";</script>
<script type="text/javascript">var _CDN_DOMAIN = location.protocol == "https:" ? "https://fs.bizspring.net" : "http://fs.bizspring.net";
        (function(b,s){var f=b.getElementsByTagName(s)[0],j=b.createElement(s);j.async=true;j.src='//fs.bizspring.net/fs4/bstrk.1.js';f.parentNode.insertBefore(j,f);})(document,'script');</script>
<noscript><img alt="Logger Script" height="1" src="http://ssl.logger.co.kr/tracker.tsp?u=39580&amp;js=N" width="1"/></noscript>
<!-- END OF LOGGER TRACKING SCRIPT -->
<!-- remove adblocks -->
<script async="" nonce="_fDQcfoeJAYbeAl_CXAg1A" src="https://fundingchoicesmessages.google.com/i/pub-1557771002660658?ers=1"></script><script nonce="_fDQcfoeJAYbeAl_CXAg1A">(function() {function signalGooglefcPresent() {if (!window.frames['googlefcPresent']) {if (document.body) {const iframe = document.createElement('iframe'); iframe.style = 'width: 0; height: 0; border: none; z-index: -1000; left: -1000px; top: -1000px;'; iframe.style.display = 'none'; iframe.name = 'googlefcPresent'; document.body.appendChild(iframe);} else {setTimeout(signalGooglefcPresent, 0);}}}signalGooglefcPresent();})();</script>
</head>
<body>
<noscript><iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-PDPW2LX" style="display:none;visibility:hidden" width="0"></iframe></noscript>
<script async="" src="//lib.wtg-ads.com/publisher/10000recipe.com/wtg_skyscraper.js" type="text/javascript"></script>
<script async="" src="//lib.wtg-ads.com/publisher/10000recipe.com/sb_ad.js" type="text/javascript"></script>
<script charset="utf-8" src="https://recipe1.ezmember.co.kr/static/js/jquery-ui-1.11.4.js" type="text/javascript"></script><link href="https://recipe1.ezmember.co.kr/static/css/jquery-ui-1.11.4_201507011.css" rel="stylesheet" type="text/css"/><script>
$(document).ready(function() {
    doRTKeyword();

    $("#srhRecipeText").keypress(function(event) {
        if (event.which == 13) {
            event.preventDefault();
            $("#frmTopRecipeSearch").submit();
        }
    }).autocomplete({
        delay: 200,
        source: "https://www.10000recipe.com/recipe/ajax.html?q_mode=autoComplete",
        focus: function(event, ui) {
            return false;
        },
        select: function(event, ui) {
            this.value = ui.item.label;
            return false;
        }
    }).focus();

    $('.ui-autocomplete').css('z-index','10000');
});



var curRtword = 2;
function doRTKeyword()
{
    var backRtword = (curRtword == 1) ? 2 : 1;
    $("#RtwordDiv_"+curRtword).hide();
    $("#RtwordDiv_"+backRtword).show();
    curRtword = backRtword;
}
</script>
<a class="rmenu_top" href="#" id="btnGogoTop" style="display:none"><span class="glyphicon glyphicon-menu-up"></span></a>
<div class="gnb" style="position: relative">
<div class="gnb_top_wrap">
<div class="gnb_top">
<h1><a href="https://www.10000recipe.com/index.html"><img alt="로고" src="https://recipe1.ezmember.co.kr/img/logo4.png"/></a></h1>
<div class="gnb_search">
<form action="https://www.10000recipe.com/recipe/list.html" id="frmTopRecipeSearch" method="get">
<div class="input-group">
<input class="form-control" id="srhRecipeText" name="q" placeholder="" style="ime-mode:active;" type="text" value=""/>
<span class="input-group-btn">
<button class="btn btn-default" onclick="$('#frmTopRecipeSearch').submit();" type="button"><span class="glyphicon glyphicon-search"></span></button>
</span>
</div>
</form>
<div class="gnb_search_word" style="display: none">
<ul id="RtwordDiv_1" style="display:none;"><li><a href="https://www.10000recipe.com/recipe/list.html?q=제육 볶음">제육 볶음</a></li><li><a href="https://www.10000recipe.com/recipe/list.html?q=두부 조림">두부 조림</a></li><li><a href="https://www.10000recipe.com/recipe/list.html?q=두부 찌개">두부 찌개</a></li><li><a href="https://www.10000recipe.com/recipe/list.html?q=닭볶음탕">닭볶음탕</a></li><li><a href="https://www.10000recipe.com/recipe/list.html?q=김치 찌개">김치 찌개</a></li></ul><ul id="RtwordDiv_2" style="display:none;"><li><a href="https://www.10000recipe.com/recipe/list.html?q=소고기 국">소고기 국</a></li><li><a href="https://www.10000recipe.com/recipe/list.html?q=무생채">무생채</a></li><li><a href="https://www.10000recipe.com/recipe/list.html?q=된장 찌개">된장 찌개</a></li><li><a href="https://www.10000recipe.com/recipe/list.html?q=두부">두부</a></li><li><a href="https://www.10000recipe.com/recipe/list.html?q=콩 나물 국">콩 나물 국</a></li></ul> <div class="gnb_search_btn">
<a href="javascript:void(0);" onclick="doRTKeyword()"><img alt="이전" src="https://recipe1.ezmember.co.kr/img/btn_arrow2_l.gif"/></a>
<a href="javascript:void(0);" onclick="doRTKeyword()"><img alt="다음" src="https://recipe1.ezmember.co.kr/img/btn_arrow2_r.gif"/></a>
</div>
</div>
</div>
<ul class="gnb_right">
<li style="position: relative;">
<div style="position: absolute; width:100px; top: 47px; left: 0; margin-left: -25px;display:none;">
<span style="margin: 0; padding: 0; font-size: 0; display: block; text-align: center;"><img src="https://recipe1.ezmember.co.kr/img/icon_arrow10.png" width="8"/></span>
<span style="border-radius: 2px; background: #ffd200; color: #000; display: block; font-size: 11px; padding:2px 5px; text-align: center;">회원가입 +3,000</span>
</div>
<a href="https://www.10000recipe.com/user/login.html?q_path=https%3A%2F%2Fwww.10000recipe.com%2Frecipe%2Flist.html"><img alt="로그인" src="https://recipe1.ezmember.co.kr/img/ico_user.png"/></a>
</li>
<li>
<a data-original-title="레시피등록" data-target="#divModalWriteForm" data-toggle="modal" href="https://www.10000recipe.com/user/login.html?q_path=https%3A%2F%2Fwww.10000recipe.com%2Frecipe%2Flist.html" title="레시피등록"><img src="https://recipe1.ezmember.co.kr/img/tmn_write.png"/></a>
</li>
<!--li style="margin-left:50px;">
                        <a href="https://market.android.com/details?id=com.ezhld.recipe" target="_blank" data-toggle="tooltip" title="" data-original-title="앱다운로드-안드로이드"><img src="https://recipe1.ezmember.co.kr/img/tmn_app_a.png"></a>
                    </li>
                    <li>
                        <a href="https://itunes.apple.com/kr/app/yoribaeggwa-mangaeyi-resipi/id494190282?mt=8" target="_blank" data-toggle="tooltip" title="" data-original-title="앱다운로드-애플"><img src="https://recipe1.ezmember.co.kr/img/tmn_app_i.png"></a>
                    </li-->
</ul>
</div>
</div>
<div class="gnb_nav">
<ul class="gnb_nav_ea10">
<li><a href="https://www.10000recipe.com/index.html">추천</a></li>
<li><a class="active" href="https://www.10000recipe.com/recipe/list.html">분류</a></li>
<li><a href="https://www.10000recipe.com/ranking/home_new.html">랭킹</a></li>
<li><a href="https://www.10000recipe.com/issue/list.html?types=magazine">매거진</a></li>
<li>
<div class="dropdown">
<a aria-expanded="false" class="dropdown-toggle" data-toggle="dropdown" href="#" id="dropdownMenu1_topMenu">더보기<span aria-hidden="true" class="glyphicon glyphicon-menu-down"></span></a>
<ul aria-labelledby="dropdownMenu1" class="dropdown-menu" role="menu" style="z-index:100000;">
<li role="presentation"><a href="https://www.10000recipe.com/event/list.html" role="menuitem" tabindex="-1">이벤트</a></li>
<li role="presentation"><a href="https://www.10000recipe.com/brand/home.html" role="menuitem" tabindex="-1">브랜드</a></li>
<li role="presentation"><a href="https://www.10000recipe.com/chef/chef_list.html" role="menuitem" tabindex="-1">쉐프</a></li>
<li role="presentation"><a href="https://www.10000recipe.com/chef/celeb_list.html" role="menuitem" tabindex="-1">만개 인플루언서</a></li>
</ul>
</div>
</li>
</ul>
</div>
</div>
<script>
var fromOther = 'n';
$(document).ready(function() {
    $(".ellipsis_title").ellipsis({row: 1});
    $(".ellipsis_title2").ellipsis({row: 2});

    $(window).scroll(function() {
        if ($(window).scrollTop() > $(window).height()*1.5) {
            $("#btnGogoTop").slideDown(300);
        } else {
            $("#btnGogoTop").slideUp(300);
        }
    });
    $('[data-toggle="tooltip"]').tooltip();
});

$(function() {
    $('#memLayerBtn').click(function (e) {
        // Used to stop the event bubbling..
        e.stopPropagation();
        if ($('.mem_layer').is(':visible')) {
            $('.mem_layer').hide();
        } else {
            $('.mem_layer').show();
        }
    });

    $(document).click(function () {
        $('.document_common_layer').hide();
    });

    $("#btnBlogContentsList").click(function() {
        $("#btnBlogContentsList").html('<span class="fa fa-spinner fa-spin" style="width:'+$("#btnBlogContentsList").width()+'px"></span>');
        el = $(this);
        var params = 'q_mode=get_blog_contents_list&q_portal='+$("[name=q_portal]:checked").val()+'&q_blogid='+$("#q_blogid").val();
        $.get("https://www.10000recipe.com/common/ajx_common.html?"+params, function(html) {
            $("#btnBlogContentsList").html('조회');
            $("#divBlogContentsList").html(html);
        });
    });
    $('#divModalBlogForm').on('show.bs.modal',function() {
        $.ajax({
            type: "POST",
            url: "https://www.10000recipe.com/common/ajx_common.html",
            data: "q_mode=get_blog_info",
            dataType: "json",
            success: function(json) {
                if (json['portal']) {
                    $("[id^=q_portal_]").filter('[value='+json['portal']+']').trigger('click');
                }
                if (json['blog_id']) {
                    $("#q_blogid").val(json['blog_id']);
                    $("#q_blog_select_type_id").trigger('click');
                }
            },
            error: function () {

            }
        });
    });
    doChangePortal('Naver');
});
var _blogIsSubmit = false;
function doChangePortal(portal) {
    var header = '';
    var tail = '';
    $("#top_blog_select_id").hide();
    $("#top_blog_select_url").hide();
    if (portal == 'Naver') {
        header = 'https://blog.naver.com/';
        tail = '';
        $("#top_blog_select_id").show();
    } else if (portal == 'Tistory') {
        header = 'https://';
        tail = '.tistory.com';
        $("#top_blog_select_id").show();
    } else if (portal == 'Direct') {
        $("#top_blog_select_url").show();
    }
    $("#txtBlogHeader").text(header);
    $("#txtBlogTail").text(tail);
    $("#q_portal_"+portal).prop("checked",true);
}

function doBlogSelect() {
    var selType = $("input[name='q_portal']:checked").val();
    if (selType == 'Direct') {
        var q_link = $("#q_blogurl").val();
        if ($.trim(q_link) == '') {
            alert('URL을 입력해 주세요.');
            $("#q_blogurl").focus();
            return;
        } else {
            setBlogContents(q_link);
        }
     } else {
        getBlogContentsList();
     }
}
function getBlogContentsList(page,added_params) {
    if (page == 0) return;
    if (!page) {
        page = 1;
    }
    if ($("#q_blogid").val() == '') {
        alert("블로그 주소를 입력해 주세요.");
        return;
    }
    //var blog_url = $("#txtBlogHeader").text() + $("#q_blogid").val() + $("#txtBlogTail");

    if (_blogIsSubmit) {
        alert("처리중 입니다. 잠시만 기다리세요.");
        return;
    }

    $("#q_page").val(page);
    _blogIsSubmit = true;
    var params = 'q_mode=get_blog_contents_list&q_portal='+$("[name=q_portal]:checked").val()+'&q_blogid='+$("#q_blogid").val()+'&q_scal='+$("#q_scal").val()+'&q_page='+page;
    if (added_params) {
        if (added_params.substring(0,1) != '&') params += '&';
        params += added_params;
    }

    $.ajax({
        type: "POST",
        cache: false,
        url: "https://www.10000recipe.com/common/ajx_common.html",
        data: params,
        success: function(html) {
            $("#divBlogContentsList").html(html);
            $("[id^=spanBlogContentsTitle_]").ellipsis();
            $('#divModalBlogContentsList').modal('show');
            _blogIsSubmit = false;
            return html;
        },
        error: function () {
            alert('예기치 못한 오류로 인해 실패했습니다.');
            _blogIsSubmit = false;
        }
    });
}
function setBlogContents(q_link) {
    if (typeof q_link == 'undefined' || q_link == '') {
        q_link = $("#listBlog [id^=q_link_]:checked").val();

        if (!q_link) {
            alert('블로그 컨텐츠를 선택하세요.');
            return;
        }
    }
    $("#btnSetBlogContents").html('<span class="fa fa-spinner fa-spin" style="width:' + $("#btnSetBlogContents").width() + 'px"></span>');
    if(fromOther == 'n') document.location.href = 'https://www.10000recipe.com/inbox/insert.html?ref_blog_url=' + encodeURIComponent(q_link);
    else if(fromOther == 'review') document.location.href = 'https://www.10000recipe.com/event/ins_review.html?seq=&review_seq=&ref_blog_url=' + encodeURIComponent(q_link);
}

function doSelWrite(tabs)
{
    $("[id^='writeSelectStep']").hide();
    $("#writeSelectStep"+tabs).show();
    $("[id^='selTabs']").removeClass('active');
    $("#selTabs"+tabs).addClass('active');
}

function doInstaSelect()
{
    if (!$("#q_insta_url").val())
    {
        $("#warnInstaMsg").html('ⓘ URL을 등록해 주세요.');
        return ;
    }
    $("#ailoading").show();
    $.ajax({
        type: "GET",
        cache: false,
        url: "https://www.10000recipe.com/common/ajx_common.html",
        data: "q_mode=get_insta_input_ai&insta_url="+$("#q_insta_url").val(),
        success: function(html) {
            var msg = '';
            if(html == 'NOT_EXIST') msg = 'ⓘ URL을 등록해 주세요.';
            else if(html == 'INVALID_URL') msg = 'ⓘ 사용할 수 없는 URL 입니다.';
            else if(html == 'DUPLICATE') msg = 'ⓘ 이미 등록된 인스타그램 URL 입니다.';
            else if(html == 'NOT_CONT') msg = 'ⓘ 내용을 분석할 수 없습니다. 다른 URL을 사용해주세요.';
            else if(html == 'FAILED' || html == '') msg = 'ⓘ 분석에 실패했습니다. 직접 등록하기를 추천드려요.';
            else if(html != '')
            {
                $("#ret_ai_desc").val(html);
                $("#goInputForm").submit();
            }
            $("#ailoading").hide();
            $("#warnInstaMsg").html(msg);
        },
        error: function () {
            alert('예기치 못한 오류로 인해 실패했습니다.');
            _blogIsSubmit = false;
        }
    });
}
</script>
<form action="https://www.10000recipe.com/inbox/insert.html" id="goInputForm" method="post" name="goInF">
<input id="ret_ai_desc" name="ai_desc" type="hidden" value=""/>
</form>
<div aria-hidden="true" aria-labelledby="myModalLabelss" class="modal fade" id="divModalWriteForm" role="dialog" style="z-index:100001" tabindex="-1">
<div class="modal-dialog">
<div class="modal-content modal_new" style="width:760px">
<div class="loader_box" id="ailoading" style="display:none;">
<span class="dots-loader">Loading…</span>
<p>AI가 내용을 분석하고 있어요.<br/>잠시만 기다려주세요.</p>
</div>
<div class="modal_new_tit">
<div class="modal_new_t_l">레시피 등록</div>
<div class="modal_new_t_r"><a aria-label="Close" class="x-icon" data-dismiss="modal" href="#"></a></div>
</div>
<div class="modal_new_cont">
<div class="modal_new_c_t">레시피 등록방법을 선택해주세요.</div>
<div class="modal_new_c regi2_btn st_lg">
<a href="https://www.10000recipe.com/inbox/insert.html"><span class="regi2_btn_w">직접등록</span></a>
<a href="javascript:void(0)" id="selTabs2" onclick="doSelWrite('2')"><span class="regi2_btn_b">블로그 레시피 가져오기</span></a>
<a href="javascript:void(0)" id="selTabs3" onclick="doSelWrite('3')"><span class="regi2_btn_v">영상 레시피 가져오기</span></a>
</div>
<div id="writeSelectStep2" style="display:none;">
<div class="modal_new_c_t">레시피를 가져올 방식을 선택해 주세요.</div>
<div class="modal_new_c">
<div class="regi2_radio pad_b_20">
<span onclick="doChangePortal('Naver')"><input id="q_portal_Naver" name="q_portal" type="radio" value="Naver"/><label>네이버</label></span>
<span onclick="doChangePortal('Tistory')"><input id="q_portal_Tistory" name="q_portal" type="radio" value="Tistory"/><label>티스토리</label></span>
<span onclick="doChangePortal('Direct')"><input id="q_portal_Direct" name="q_portal" type="radio" value="Direct"/><label>URL직접입력</label></span>
</div>
<!--네이버블로그 선택시-->

## 레시피명

In [357]:
title = soup.select('div.common_sp_caption_tit.line2')
len(title)
title[2].text

'김치 제육볶음 레시피｜저녁메뉴로 딱! 실패 없는 제육볶음 양념 만드는법'

## 작성자

In [341]:
name = soup.select('div.common_sp_caption_rv_name')
len(name)

40

## 조회수

In [352]:
view = soup.select('span.common_sp_caption_buyer')
len(view)
view[5].text.split(' ')[1:]

['5.2만']

In [383]:
title_list, name_list, view_list = [], [], []

for i in range(len(title)):
    title_list.append(title[i].text.strip())
    name_list.append(name[i].text.strip())
    view_list.append(view[i].text.strip()[4:])

In [384]:
recipe_dic = {'제목':title_list,
             '작성자':name_list,
             '조회수':view_list}

df = pd.DataFrame(recipe_dic, index=range(1, len(title)+1))
df.index.name = 'No'
df

                                         제목        작성자    조회수
No
1                [매운요리] 김치 야채 참치찌개 매콤참치김치찌개      뿡씨스터즈     66
2                      전자레인지로 간단하게! 버터간장계란밥        뽕림이    261
3   김치 제육볶음 레시피｜저녁메뉴로 딱! 실패 없는 제육볶음 양념 만드는법        몽글쿡    180
4               굴소스 팽이버섯 계란 덮밥 만들기 한 그릇 레시피        Y큰손  3,893
5                  10분 만에 초간단 명란 버터 파스타 만들기         밀집     62
6                         새송이버섯버터굴소스볶음 간단반찬        라피네   5.2만
7                      도시락 반찬으로 최고! 스팸감자조림♡     냠냠간단요리  10.4만
8       오이고추된장무침 (사계절 먹기좋은 밑반찬 고추무침 5분 레시피)  ariel1007   2.8만
9                           양배추 오믈렛/다이어트 식단        잔근육    897
10                       매운빨간콩나물무침 레시피 매일반찬        라피네   1.2만
11             아이반찬 양파소세지볶음 레시피 양파요리 초스피드반찬        라피네   3.1만
12     시금치무침 (시금치데치는 방법 시금치나물요리 나물반찬 반찬레시피)  ariel1007   1.4만
13               단무지무침 레시피 밑반찬 만들기 치자 단무지무침        써지니    498
14                              청경채 된장 무침으로     요리재능발견   3.4만
15                       즉석,오이 부추 무침(백종원양념)      달콤스윗맘   1.5만
16                         도토리묵김무침 레시피 아이반찬        라피네   2.9만
17                              #최애반찬#소세지강정        심킹카  16.1만
18                                 베이컨감자채볶음       승일승훈   2.2만
19    고소한 맛이 좋은 밑반찬, 애호박버섯볶음 만들기(새우젓없이 만들기)       꼬꼬부기   5.3만
20                               간장버터 새송이구이   요리하는허니레빗  9,805
21                               목살김치찜 만드는법   랴니의간단레시피    296
22                    저렴하게 반찬 뚝딱!! 감자조림 만들기      한입만아내  5,284
23                   여름반찬 아삭오이고추 만능된장무침 레시피     햇살머금은집   1.2만
24                      [참치쌈장] 입맛없을때 밥도둑이요!      유튜버아뜨   1.9만
25                    시금치 계란 볶음 레시피 다이어트 반찬      춤추는루나     2만
26                   내 인생 레시피,친정 엄마표 “파채무침”      달콤스윗맘     4만
27      향긋한 취나물 간단하게 쌈장으로 무쳐도 맛있어요, 취나물쌈장무침     만개의레시피  8,133
28           [밑반찬] 10분 밑반찬 딱딱하지않고 부드러운 오징어채        븟린이   2.7만
29                   새송이버섯볶음 간장버섯조림 어린이 밑반찬         뚜루   2.7만
30                          단짠단짠 마성의 베이컨덮밥♡     냠냠간단요리   2.7만
31        버섯으로 관자 느낌 내는 방법! 새송이버섯간장버터구이 만들기         루던  41.6만
32                    베이컨 떡말이 어린이 간식 간단 술안주         뚜루     1만
33                       삼겹살 싸 먹기 좋은 봄동 겉절이  내맛대로요리레시피  3,129
34                      차돌박이떡볶음으로 즐기는 특별한요리   푸드디렉터요알남  2,738
35            NO밀가루! 감자치즈호떡 아이들 간식으로 딱 좋아요.     만개의레시피   1.6만
36      아이 반찬 콩나물 & 크래미 무침 - 아이들 콩나물과 친해져요.      춤추는루나   2.2만
37                                  "시금치나물"       밥차리라  1,890
38                     애호박새우살볶음 한끼반찬 초스피드요리        라피네   1.6만
39                  간단하고 맛있게 대파소시지달걀볶음밥 만들기        레몬콩  9,834
40         소떡강정 만드는 법 소떡소떡보다 만들기 쉬운 소떡강정레시피        라피네   4.2만

## 이제 1~10 p의 데이터를 모두 수집해보자!
- page의 경우 GET 방식의 웹사이트는 url에 정보가 표시되므로, 해당 정보가 어디있는지 파악해 볼 것

In [390]:
# tqdm: 반복문의 진행상황을 로딩바로 확인하게 해주는 모듈 
from tqdm import tqdm

In [ ]:
https://www.10000recipe.com/recipe/list.html?order=reco&page=3

In [393]:
titles_list, authors_list, views_list = [], [], []

for i in tqdm(range(1,11,1)) :
    # 1~10page에 반복적으로 접근
    url = f'https://www.10000recipe.com/recipe/list.html?order=reco&page={i}'
    res = requests.get(url, headers=U_A)
    soup = bs(res.text, 'lxml')

    titles = soup.select('div.common_sp_caption_tit.line2')
    authors = soup.select('div.common_sp_caption_rv_name > a')
    views = soup.select('span.common_sp_caption_buyer')

    for i in range(len(titles)) :
        titles_list.append(titles[i].text.strip())
        authors_list.append(authors[i].text.strip())
        views_list.append(views[i].text.strip()[4:])

recipe_dict = {'레시피명':titles_list, '작성자':authors_list, '조회수':views_list}
recipe_df = pd.DataFrame(recipe_dict, index=range(1,len(titles_list)+1))
recipe_df.index.name = 'No'
recipe_df

100%|██████████████████████████████████████████████████████████████████████████████████| 10/10 [00:16<00:00,  1.62s/it]

                                        레시피명     작성자    조회수
No
1                 [매운요리] 김치 야채 참치찌개 매콤참치김치찌개   뿡씨스터즈     70
2                       전자레인지로 간단하게! 버터간장계란밥     뽕림이    263
3    김치 제육볶음 레시피｜저녁메뉴로 딱! 실패 없는 제육볶음 양념 만드는법     몽글쿡    180
4                굴소스 팽이버섯 계란 덮밥 만들기 한 그릇 레시피     Y큰손  3,897
5                   10분 만에 초간단 명란 버터 파스타 만들기      밀집     62
..                                       ...     ...    ...
396              가츠동 대신 비비고 만두로 계란 만두 덮밥 만들기   요리조리콩  5,618
397            모닝빵 속에 옥수수가 ★ 에어프라이어 옥수수치즈빵 ★  만개의레시피  11.6만
398                   두부시금치무침 이 레시피가 제일 맛있네요  o세실리아o  45.3만
399                                  연두부 샐러드   가는동자꽃  24.6만
400        명란찜 만드는 법 밥도둑 명란젓갈찜 레시피 초간단 반찬 요리     포남댁    550

[400 rows x 3 columns]

In [401]:
filtered_df = recipe_df[recipe_df['레시피명'].str.contains('김치')]

# reset_index : 인덱스 재설정
filtered_df.reset_index(drop=True, inplace=True)
filtered_df.index = range(1, len(filtered_df)+1)
filtered_df

                                       레시피명       작성자    조회수
1                [매운요리] 김치 야채 참치찌개 매콤참치김치찌개     뿡씨스터즈     70
2   김치 제육볶음 레시피｜저녁메뉴로 딱! 실패 없는 제육볶음 양념 만드는법       몽글쿡    180
3                                목살김치찜 만드는법  랴니의간단레시피    297
4                            참기름 스팸김치볶음 레시피     평범한흔남   1.1만
5                       [붉은요리] 스팸 김치볶음밥 레시피        뚜루    251
6                        보글보글 묵은지 돼지고기 김치찌개   난이가있는그곳    252
7                                    김치 삼겹살      쿠킹조이  5,226
8                 베이컨김치볶음밥 레시피 간단 김치볶음밥 만들기       심플민    825
9                            든든한 혼밥 돈까스김치나베    순둥이요리사  14.3만
10                  마지막 묵은지 털어 끓인 김치 콩나물국..    윤씨네삼남매   1.1만

## 함수로 코드 통합하기

In [1]:
# 매개변수는 검색할 최종페이지, 필터링 할 검색어 (디폴트로 빈 문자열)
# 반환할 자료형은 DataFrame을 명시
def search_recipe(end_page:int, search:str='') -> pd.DataFrame:
    
    titles_list, authors_list, views_list = [], [], []

    for i in tqdm(range(1, end_page+1, 1)) :
        # 1~10page에 반복적으로 접근
        url = f'https://www.10000recipe.com/recipe/list.html?order=reco&page={i}'
        res = requests.get(url, headers=U_A)
        soup = bs(res.text, 'lxml')
    
        titles = soup.select('div.common_sp_caption_tit.line2')
        authors = soup.select('div.common_sp_caption_rv_name > a')
        views = soup.select('span.common_sp_caption_buyer')
    
        for i in range(len(titles)) :
            titles_list.append(titles[i].text.strip())
            authors_list.append(authors[i].text.strip())
            views_list.append(views[i].text.strip()[4:])
    
    recipe_dict = {'레시피명':titles_list, '작성자':authors_list, '조회수':views_list}
    recipe_df = pd.DataFrame(recipe_dict, index=range(1,len(titles_list)+1))

    # 검색어가 존재할 경우!
    if search:
        # copy: 기존 객체를 복사
        filtered_df = recipe_df[recipe_df['레시피명'].str.contains(f'{search}')].copy()
    # 검색어 없으면
    else:
        # 기존 recipe_df를 그대로 사용
        filtered_df = recipe_df.copy()

    filtered_df.reset_index(drop=True, inplace=True)
    filtered_df.index = range(1, len(filtered_df)+1)
    return filtered_df

NameError: name 'pd' is not defined

In [409]:
search_recipe(2)

100%|████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.51s/it]

                                       레시피명    작성자    조회수
1                [매운요리] 김치 야채 참치찌개 매콤참치김치찌개  뿡씨스터즈     77
2                      전자레인지로 간단하게! 버터간장계란밥    뽕림이    268
3   김치 제육볶음 레시피｜저녁메뉴로 딱! 실패 없는 제육볶음 양념 만드는법    몽글쿡    187
4               굴소스 팽이버섯 계란 덮밥 만들기 한 그릇 레시피    Y큰손  3,899
5                  10분 만에 초간단 명란 버터 파스타 만들기     밀집     62
..                                      ...    ...    ...
76                          쪽파계란말이 만들기-딸에게#   노란장미   1.2만
77               새콤달콤 무생채 레시피 아삭한 무생채 만드는 법    심플민   1.1만
78                          고소하고 향긋한 깻잎들깨볶음    콩설기  16.6만
79             스팸 돈부리덮밥!반찬이 필요없는 초간단 한그릇 요리   뽀유TV  33.5만
80                    매운 어묵볶음 어묵 요리 맛있게 만들기     오즈  9,764

[80 rows x 3 columns]